project_id = "jxpbiljkoibvqxzdkgod"

[functions.send-opportunity-notification]
verify_jwt = true

[functions.track-opportunity-analytics]
verify_jwt = true

[functions.secure-upload]

[functions.cleanup-temp-files]
verify_jwt = true

[functions.unsplash-images]
verify_jwt = false