project_id = "jxpbiljkoibvqxzdkgod"

[functions.calculate-profile-completion]
verify_jwt = true

[functions.elevate-user-privileges]
verify_jwt = false

[functions.send-opportunity-notification]
verify_jwt = true

[functions.track-opportunity-analytics]
verify_jwt = true

[functions.secure-upload]

[functions.cleanup-temp-files]
verify_jwt = true

[functions.unsplash-images]
verify_jwt = false

[functions.migrate-storage-buckets]
verify_jwt = true

[functions.comprehensive-storage-migration]
verify_jwt = true

[functions.create-paddle-checkout]
verify_jwt = true

[functions.check-paddle-subscription]
verify_jwt = true

[functions.logflare-analytics]
verify_jwt = true

[functions.ai-content-moderation]
verify_jwt = false

[functions.ai-tag-suggestions]
verify_jwt = false

[functions.ai-semantic-search]
verify_jwt = false

[functions.update-translations]
verify_jwt = false

[functions.send-challenge-notification]
verify_jwt = false

[functions.challenge-analytics-tracker]
verify_jwt = false

[functions.real-time-presence-manager]
verify_jwt = false

[functions.challenge-workflow-manager]
verify_jwt = false

[functions.ai-content-generator]
verify_jwt = false

[functions.generate-analytics-report]
verify_jwt = false

[functions.send-event-notification]
verify_jwt = false

[functions.send-idea-notification]
verify_jwt = false

[functions.ai-tag-generator]
verify_jwt = false

[functions.social-media-publisher]
verify_jwt = false