project_id = "jxpbiljkoibvqxzdkgod"

[functions.send-opportunity-notification]
verify_jwt = true

[functions.track-opportunity-analytics]
verify_jwt = true

[functions.secure-upload]
verify_jwt = true