-- Insert new admin and events translation keys
INSERT INTO system_translations (translation_key, text_en, text_ar, category) VALUES

-- Storage Quota Manager translations
('error.validation', 'Validation Error', 'خطأ في التحقق', 'admin'),
('storage.quota.select_bucket_size', 'Please select a bucket and enter quota size', 'يرجى اختيار حاوية وإدخال حجم الحصة', 'admin'),
('storage.quota.set_success', 'Quota Set', 'تم تعيين الحصة', 'admin'),
('storage.quota.removed', 'Quota Removed', 'تم إزالة الحصة', 'admin'),
('storage.quota.auto_setup_complete', 'Auto Setup Complete', 'اكتمل الإعداد التلقائي', 'admin'),
('storage.quota.auto_setup_failed', 'Auto Setup Failed', 'فشل الإعداد التلقائي', 'admin'),
('storage.quotas.title', 'Storage Quotas', 'حصص التخزين', 'admin'),
('storage.quotas.description', 'Manage storage quotas for different buckets', 'إدارة حصص التخزين للحاويات المختلفة', 'admin'),
('storage.quota.add', 'Add Quota', 'إضافة حصة', 'admin'),
('storage.quota.set_title', 'Set Storage Quota', 'تعيين حصة التخزين', 'admin'),
('storage.bucket', 'Bucket', 'الحاوية', 'admin'),
('storage.select_bucket', 'Select a bucket', 'اختر حاوية', 'admin'),
('storage.quota.size', 'Quota Size', 'حجم الحصة', 'admin'),
('storage.quota.size_placeholder', '100', '100', 'admin'),
('storage.unit', 'Unit', 'الوحدة', 'admin'),
('storage.quota.set', 'Set Quota', 'تعيين الحصة', 'admin'),
('storage.quota.none_configured', 'No storage quotas configured', 'لم يتم تكوين حصص تخزين', 'admin'),
('storage.quota.auto_setup', 'Auto Setup (5GB Default)', 'إعداد تلقائي (5 جيجا افتراضي)', 'admin'),
('storage.used', 'used', 'مستخدم', 'admin'),
('storage.total', 'total', 'إجمالي', 'admin'),
('storage.quota.exceeded', 'Quota exceeded! Current usage is {{amount}} over the limit.', 'تم تجاوز الحصة! الاستخدام الحالي {{amount}} فوق الحد المسموح.', 'admin'),

-- Translation Manager translations
('translations.delete_confirm', 'Are you sure you want to delete this translation?', 'هل أنت متأكد من حذف هذه الترجمة؟', 'admin'),
('translations.json_download', 'JSON Download', 'تنزيل JSON', 'admin'),
('translations.json_download_desc', 'Download translation JSON files for manual deployment', 'تنزيل ملفات JSON للترجمة للنشر اليدوي', 'admin'),
('translations.manual_process', 'Manual Process Required', 'مطلوب عملية يدوية', 'admin'),
('translations.manual_process_desc', 'After downloading, manually replace the JSON files in src/i18n/locales/ to update static translations.', 'بعد التنزيل، استبدل ملفات JSON يدوياً في src/i18n/locales/ لتحديث الترجمات الثابتة.', 'admin'),
('translations.download_english', 'Download English JSON', 'تنزيل JSON الإنجليزية', 'admin'),
('translations.download_arabic', 'Download Arabic JSON', 'تنزيل JSON العربية', 'admin'),
('translations.bilingual_management', 'Bilingual Translation Management', 'إدارة الترجمة ثنائية اللغة', 'admin'),
('translations.bilingual_desc', 'Manage bilingual translations (English and Arabic in single records)', 'إدارة الترجمات ثنائية اللغة (الإنجليزية والعربية في سجلات واحدة)', 'admin'),
('translations.search_placeholder', 'Search translations...', 'ابحث في الترجمات...', 'admin'),
('translations.add', 'Add Translation', 'إضافة ترجمة', 'admin'),
('translations.no_translations_found', 'No translations found', 'لم يتم العثور على ترجمات', 'admin'),
('translations.edit', 'Edit Translation', 'تعديل الترجمة', 'admin'),
('translations.key', 'Translation Key', 'مفتاح الترجمة', 'admin'),
('translations.key_placeholder', 'e.g., settings.ui.theme', 'مثال: settings.ui.theme', 'admin'),
('translations.english_text', 'English Text', 'النص الإنجليزي', 'admin'),
('translations.english_placeholder', 'Enter English text', 'أدخل النص الإنجليزي', 'admin'),
('translations.arabic_text', 'Arabic Text', 'النص العربي', 'admin'),
('translations.arabic_placeholder', 'أدخل النص العربي', 'أدخل النص العربي', 'admin'),

-- Translation System Status translations
('translation.cache.refresh_success', 'Translation cache refreshed successfully', 'تم تحديث ذاكرة التخزين المؤقت للترجمة بنجاح', 'admin'),
('translation.cache.refresh_error', 'Failed to refresh translation cache', 'فشل في تحديث ذاكرة التخزين المؤقت للترجمة', 'admin'),

-- Events translations for AdminEventCard
('events.status.scheduled', 'Scheduled', 'مجدول', 'events'),
('events.status.ongoing', 'Ongoing', 'جاري', 'events'),
('events.status.completed', 'Completed', 'مكتمل', 'events'),
('events.status.cancelled', 'Cancelled', 'ملغي', 'events'),
('events.status.upcoming', 'Upcoming', 'قادم', 'events'),
('events.location.online', 'Online', 'عبر الإنترنت', 'events'),
('events.registration.limited', 'Limited', 'محدود', 'events'),
('events.registration.title', 'Registration', 'التسجيل', 'events'),
('events.registration.full', 'full', 'ممتلئ', 'events'),
('events.registration.limited_spots', 'Limited spots', 'أماكن محدودة', 'events'),
('events.registration.rate', 'Registration rate', 'معدل التسجيل', 'events'),
('events.stats.registered', 'Registered', 'مسجل', 'events'),
('events.stats.attended', 'Attended', 'حضر', 'events'),
('events.budget.free', 'Free', 'مجاني', 'events'),
('events.budget.title', 'Budget', 'الميزانية', 'events'),

-- Events translations for AdminEventsHero
('events.metrics.total', 'Total Events', 'إجمالي الفعاليات', 'events'),
('events.metrics.trend_month', '+12% from last month', '+12% من الشهر الماضي', 'events'),
('events.metrics.active', 'Active Events', 'الفعاليات النشطة', 'events'),
('events.metrics.ongoing_now', '{{count}} ongoing now', '{{count}} جارية الآن', 'events'),
('events.metrics.participants', 'Total Participants', 'إجمالي المشاركين', 'events'),
('events.metrics.registration_rate', '+8% registration rate', '+8% معدل التسجيل', 'events'),
('events.metrics.revenue', 'Revenue', 'الإيرادات', 'events'),
('events.metrics.revenue_growth', '+15% from last month', '+15% من الشهر الماضي', 'events'),
('events.venues', 'Venues', 'المواقع', 'events'),
('events.need_attention', 'Need Attention', 'تحتاج انتباه', 'events'),
('events.quick_stats', 'Quick Stats', 'إحصائيات سريعة', 'events'),
('events.status_distribution', 'Event Status Distribution', 'توزيع حالة الفعاليات', 'events'),

-- Common translations
('common.delete', 'Delete', 'حذف', 'ui'),
('common.view', 'View', 'عرض', 'ui'),
('common.edit', 'Edit', 'تعديل', 'ui'),
('common.refresh', 'Refresh', 'تحديث', 'ui'),
('common.category', 'Category', 'الفئة', 'ui'),
('common.all_categories', 'All Categories', 'جميع الفئات', 'ui'),
('common.cancel', 'Cancel', 'إلغاء', 'ui'),
('common.update', 'Update', 'تحديث', 'ui'),
('common.create', 'Create', 'إنشاء', 'ui'),
('common.currency.sar', 'SAR', 'ر.س', 'ui'),
('success', 'Success', 'نجح', 'ui'),
('error', 'Error', 'خطأ', 'ui')

ON CONFLICT (translation_key) DO UPDATE SET
  text_en = EXCLUDED.text_en,
  text_ar = EXCLUDED.text_ar,
  category = EXCLUDED.category,
  updated_at = now();