-- Challenge form translations batch
INSERT INTO system_translations (translation_key, text_en, text_ar, category) VALUES
('challenge_form.create_challenge', 'Create Challenge', 'إنشاء تحدي', 'challenge_form'),
('challenge_form.edit_challenge', 'Edit Challenge', 'تعديل التحدي', 'challenge_form'),
('challenge_form.create_challenge_description', 'Create a new innovation challenge to engage participants', 'قم بإنشاء تحدي ابتكار جديد لإشراك المشاركين', 'challenge_form'),
('challenge_form.edit_challenge_description', 'Modify the challenge details and settings', 'تعديل تفاصيل التحدي والإعدادات', 'challenge_form'),
('challenge_form.challenge_title', 'Challenge Title', 'عنوان التحدي', 'challenge_form'),
('challenge_form.challenge_title_placeholder', 'Enter the challenge title in Arabic', 'أدخل عنوان التحدي باللغة العربية', 'challenge_form'),
('challenge_form.challenge_title_en', 'Challenge Title (English)', 'عنوان التحدي (إنجليزي)', 'challenge_form'),
('challenge_form.challenge_title_en_placeholder', 'Enter the challenge title in English', 'أدخل عنوان التحدي باللغة الإنجليزية', 'challenge_form'),
('challenge_form.challenge_description', 'Challenge Description', 'وصف التحدي', 'challenge_form'),
('challenge_form.challenge_description_placeholder', 'Describe the challenge objectives and requirements', 'اوصف أهداف التحدي ومتطلباته', 'challenge_form'),
('challenge_form.challenge_description_en', 'Challenge Description (English)', 'وصف التحدي (إنجليزي)', 'challenge_form'),
('challenge_form.challenge_description_en_placeholder', 'Describe the challenge in English', 'اوصف التحدي باللغة الإنجليزية', 'challenge_form'),
('challenge_form.challenge_type', 'Challenge Type', 'نوع التحدي', 'challenge_form'),
('challenge_form.select_challenge_type', 'Select challenge type', 'اختر نوع التحدي', 'challenge_form'),
('challenge_form.priority_level', 'Priority Level', 'مستوى الأولوية', 'challenge_form'),
('challenge_form.select_priority', 'Select priority level', 'اختر مستوى الأولوية', 'challenge_form'),
('challenge_form.estimated_budget', 'Estimated Budget', 'الميزانية المقدرة', 'challenge_form'),
('challenge_form.budget_placeholder', 'Enter estimated budget in SAR', 'أدخل الميزانية المقدرة بالريال السعودي', 'challenge_form'),
('challenge_form.start_date', 'Start Date', 'تاريخ البداية', 'challenge_form'),
('challenge_form.end_date', 'End Date', 'تاريخ النهاية', 'challenge_form'),
('challenge_form.max_participants', 'Maximum Participants', 'الحد الأقصى للمشاركين', 'challenge_form'),
('challenge_form.max_participants_placeholder', 'Enter maximum number of participants', 'أدخل الحد الأقصى لعدد المشاركين', 'challenge_form'),
('challenge_form.tags', 'Tags', 'العلامات', 'challenge_form'),
('challenge_form.challenge_image', 'Challenge Image', 'صورة التحدي', 'challenge_form'),
('challenge_form.saving', 'Saving...', 'جاري الحفظ...', 'challenge_form'),
('challenge_form.save_changes', 'Save Changes', 'حفظ التغييرات', 'challenge_form')
ON CONFLICT (translation_key) DO NOTHING;