-- Add missing User Management translation keys
INSERT INTO system_translations (translation_key, text_en, text_ar, category) VALUES
('fromLastMonth', 'from last month', 'من الشهر الماضي', 'general'),
('expertUsers', 'Expert Users', 'المستخدمون الخبراء', 'users'),
('users', 'Users', 'المستخدمون', 'users'),
('totalUsers', 'Total Users', 'إجمالي المستخدمين', 'users'),
('activeUsers', 'Active Users', 'المستخدمون النشطون', 'users'),
('pendingInvitations', 'Pending Invitations', 'الدعوات المعلقة', 'users'),
('teamMembers', 'Team Members', 'أعضاء الفريق', 'users'),
('userManagement', 'User Management', 'إدارة المستخدمين', 'users'),
('manageUsersRolesPermissions', 'Manage users, roles and permissions', 'إدارة المستخدمين والأدوار والصلاحيات', 'users'),
('inviteUser', 'Invite User', 'دعوة مستخدم', 'users'),
('bulkActions', 'Bulk Actions', 'الإجراءات المجمعة', 'general'),
('searchUsers', 'Search users...', 'البحث عن المستخدمين...', 'users'),
('filterByStatus', 'Filter by status', 'تصفية حسب الحالة', 'general'),
('filterByRole', 'Filter by role', 'تصفية حسب الدور', 'general'),
('allStatus', 'All Status', 'جميع الحالات', 'general'),
('allRoles', 'All Roles', 'جميع الأدوار', 'general'),
('admin', 'Admin', 'مدير', 'roles'),
('expert', 'Expert', 'خبير', 'roles'),
('innovator', 'Innovator', 'مبتكر', 'roles'),
('role', 'Role', 'الدور', 'general'),
('department', 'Department', 'القسم', 'general'),
('lastLogin', 'Last Login', 'آخر تسجيل دخول', 'users'),
('neverLoggedIn', 'Never logged in', 'لم يسجل الدخول مطلقاً', 'users'),
('editProfile', 'Edit Profile', 'تعديل الملف الشخصي', 'users'),
('manageRole', 'Manage Role', 'إدارة الدور', 'users'),
('sendInvitation', 'Send Invitation', 'إرسال دعوة', 'users'),
('name', 'Name', 'الاسم', 'general'),
('email', 'Email', 'البريد الإلكتروني', 'general'),
('status', 'Status', 'الحالة', 'general'),
('active', 'Active', 'نشط', 'general'),
('pending', 'Pending', 'معلق', 'general'),
('inactive', 'Inactive', 'غير نشط', 'general')
ON CONFLICT (translation_key) DO UPDATE SET
  text_en = EXCLUDED.text_en,
  text_ar = EXCLUDED.text_ar,
  category = EXCLUDED.category,
  updated_at = now();