-- Advanced search and remaining translations batch
INSERT INTO system_translations (translation_key, text_en, text_ar, category) VALUES
('advanced_search.title', 'Advanced Search', 'البحث المتقدم', 'advanced_search'),
('advanced_search.filters_active', 'Filters Active', 'مرشحات نشطة', 'advanced_search'),
('advanced_search.search_query', 'Search Query', 'استعلام البحث', 'advanced_search'),
('advanced_search.search_placeholder', 'Enter keywords to search...', 'أدخل الكلمات المفتاحية للبحث...', 'advanced_search'),
('advanced_search.status', 'Status', 'الحالة', 'advanced_search'),
('advanced_search.select_status', 'Select status', 'اختر الحالة', 'advanced_search'),
('advanced_search.all_statuses', 'All Statuses', 'جميع الحالات', 'advanced_search'),
('advanced_search.priority', 'Priority', 'الأولوية', 'advanced_search'),
('advanced_search.select_priority', 'Select priority', 'اختر الأولوية', 'advanced_search'),
('advanced_search.all_priorities', 'All Priorities', 'جميع الأولويات', 'advanced_search'),
('advanced_search.date_range', 'Date Range', 'نطاق التاريخ', 'advanced_search'),
('advanced_search.start_date', 'Start Date', 'تاريخ البداية', 'advanced_search'),
('advanced_search.end_date', 'End Date', 'تاريخ النهاية', 'advanced_search'),
('advanced_search.budget_range', 'Budget Range', 'نطاق الميزانية', 'advanced_search'),
('advanced_search.minimum_budget', 'Minimum Budget', 'الحد الأدنى للميزانية', 'advanced_search'),
('advanced_search.maximum_budget', 'Maximum Budget', 'الحد الأقصى للميزانية', 'advanced_search'),
('advanced_search.tag_selector_coming_soon', 'Tag selector coming soon', 'منتقي العلامات قريباً', 'advanced_search'),
('advanced_search.search', 'Search', 'بحث', 'advanced_search'),
('advanced_search.clear_filters', 'Clear Filters', 'مسح المرشحات', 'advanced_search'),
('error.validation_error', 'Validation Error', 'خطأ في التحقق', 'error'),
('error.load_failed', 'Failed to load data', 'فشل في تحميل البيانات', 'error'),
('error.delete_failed', 'Failed to delete item', 'فشل في حذف العنصر', 'error'),
('success.delete_success', 'Successfully Deleted', 'تم الحذف بنجاح', 'success'),
('success.challenge_deleted', 'Challenge has been deleted successfully', 'تم حذف التحدي بنجاح', 'success'),
('status.draft', 'Draft', 'مسودة', 'status'),
('status.active', 'Active', 'نشط', 'status'),
('status.completed', 'Completed', 'مكتمل', 'status'),
('status.cancelled', 'Cancelled', 'ملغي', 'status'),
('status.on_hold', 'On Hold', 'معلق', 'status'),
('description', 'Description', 'الوصف', 'general'),
('vision_2030_goal', 'Vision 2030 Goal', 'هدف رؤية 2030', 'general'),
('collaboration_details', 'Collaboration Details', 'تفاصيل التعاون', 'general'),
('total_users', 'Total Users', 'إجمالي المستخدمين', 'dashboard'),
('storage.auto_cleanup', 'Auto Cleanup', 'التنظيف التلقائي', 'storage'),
('storage.cleanup_days', 'Cleanup Days', 'أيام التنظيف', 'storage'),
('storage.compression', 'Compression', 'الضغط', 'storage'),
('workspace.partner.deadline', 'Deadline', 'الموعد النهائي', 'workspace')
ON CONFLICT (translation_key) DO NOTHING;