-- Add missing translation keys for settings
INSERT INTO system_translations (translation_key, text_en, text_ar, category) VALUES
('settings.allow_open_campaign_registration.description', 'Allow users to register for campaigns without requiring approval', 'السماح للمستخدمين بالتسجيل في الحملات دون الحاجة لموافقة', 'settings'),
('settings.enable_automatic_notifications.description', 'Automatically send notifications for important events', 'إرسال الإشعارات تلقائياً للأحداث المهمة', 'settings'),
('settings.category.Challenge Management', 'Challenge Management', 'إدارة التحديات', 'settings'),
('settings.challenge_details_description_rows.description', 'Number of textarea rows for challenge description', 'عدد صفوف منطقة النص لوصف التحدي', 'settings'),
('settings.challenge_default_duration_days.description', 'Default duration for challenges in days', 'المدة الافتراضية للتحديات بالأيام', 'settings'),
('settings.challenge_default_submission_limit.description', 'Default limit for challenge submissions', 'الحد الافتراضي لإرسالات التحديات', 'settings'),
('settings.challenge_digital_maturity_score_max.description', 'Maximum digital maturity score', 'أقصى درجة للنضج الرقمي', 'settings'),
('settings.challenge_digital_maturity_score_max.label', 'Maximum Digital Maturity Score', 'أقصى درجة للنضج الرقمي', 'settings'),
('settings.challenge_digital_maturity_score_min.description', 'Minimum digital maturity score', 'أدنى درجة للنضج الرقمي', 'settings'),
('settings.challenge_digital_maturity_score_min.label', 'Minimum Digital Maturity Score', 'أدنى درجة للنضج الرقمي', 'settings'),
('settings.challenge_max_submissions_per_challenge.description', 'Maximum submissions allowed per challenge', 'أقصى عدد إرسالات مسموح لكل تحدي', 'settings'),
('settings.challenge_max_submissions_per_challenge.label', 'Maximum Submissions Per Challenge', 'أقصى عدد إرسالات لكل تحدي', 'settings'),
('settings.challenge_filter_status_options.description', 'Available status options for filtering challenges', 'خيارات الحالة المتاحة لتصفية التحديات', 'settings'),
('settings.category.Expert Management', 'Expert Management', 'إدارة الخبراء', 'settings'),
('settings.category.Expert Management.description', 'Manage expert settings and configurations', 'إدارة إعدادات وتكوينات الخبراء', 'settings'),
('settings.expert_assignment_bulk_notes_rows.description', 'Number of textarea rows for bulk expert assignment notes', 'عدد صفوف منطقة النص لملاحظات تعيين الخبراء المجمعة', 'settings'),
('settings.expert_expertise_preview_limit.description', 'Maximum number of expertise items to show in preview', 'أقصى عدد عناصر الخبرة للعرض في المعاينة', 'settings'),
('settings.expert_workload_warning_threshold.description', 'Workload percentage threshold for expert warnings', 'عتبة النسبة المئوية لعبء العمل لتحذيرات الخبراء', 'settings'),
('settings.focus_question_max_per_challenge.description', 'Maximum number of focus questions per challenge', 'أقصى عدد أسئلة التركيز لكل تحدي', 'settings'),
('settings.focus_question_require_description.description', 'Require description for focus questions', 'إجبارية وصف أسئلة التركيز', 'settings'),
('settings.idea_allow_anonymous_submissions.description', 'Allow users to submit ideas anonymously', 'السماح للمستخدمين بإرسال أفكار مجهولة الهوية', 'settings'),
('settings.idea_collaboration_invite_expiry_hours.description', 'Hours before collaboration invitations expire', 'عدد الساعات قبل انتهاء دعوات التعاون', 'settings'),
('settings.idea_collaboration_invite_expiry_hours.label', 'Collaboration Invite Expiry Hours', 'ساعات انتهاء دعوة التعاون', 'settings'),
('settings.idea_comments_moderation_enabled.description', 'Enable moderation for idea comments', 'تفعيل الإشراف على تعليقات الأفكار', 'settings'),
('settings.idea_comments_public_by_default.description', 'Make idea comments public by default', 'جعل تعليقات الأفكار عامة افتراضياً', 'settings'),
('settings.idea_evaluation_criteria_weights.description', 'Weights for different evaluation criteria', 'أوزان معايير التقييم المختلفة', 'settings'),
('settings.idea_evaluation_multiple_allowed.description', 'Allow multiple evaluations for the same idea', 'السماح بتقييمات متعددة للفكرة الواحدة', 'settings'),
('settings.idea_evaluation_require_comments.description', 'Require comments when evaluating ideas', 'إجبارية التعليقات عند تقييم الأفكار', 'settings'),
('settings.idea_implementation_tracking_enabled.description', 'Enable tracking of idea implementation progress', 'تفعيل تتبع تقدم تنفيذ الأفكار', 'settings'),
('settings.idea_implementation_tracking_enabled.label', 'Idea Implementation Tracking', 'تتبع تنفيذ الأفكار', 'settings'),
('settings.idea_lifecycle_milestones_enabled.description', 'Enable lifecycle milestones for ideas', 'تفعيل معالم دورة حياة الأفكار', 'settings'),
('settings.idea_milestone_notifications_enabled.description', 'Send notifications when idea milestones are reached', 'إرسال إشعارات عند الوصول لمعالم الأفكار', 'settings'),
('settings.idea_milestone_notifications_enabled.label', 'Idea Milestone Notifications', 'إشعارات معالم الأفكار', 'settings')
ON CONFLICT (translation_key) DO UPDATE SET
text_en = EXCLUDED.text_en,
text_ar = EXCLUDED.text_ar,
category = EXCLUDED.category,
updated_at = NOW();