-- Add comprehensive workspace translations to support full workspace functionality

INSERT INTO translations (key, value_ar, value_en, category, description) VALUES

-- Workspace Core Concepts
('workspace_vs_dashboard_explanation', 'مساحة العمل هي بيئة عمل نشطة للإنتاجية والتعاون، بينما لوحة التحكم هي مركز مراقبة للمعلومات والتحليلات', 'Workspace is an active work environment for productivity and collaboration, while dashboard is a monitoring center for information and analytics', 'workspace', 'Explains the difference between workspace and dashboard'),

('active_work_environment', 'بيئة عمل نشطة', 'Active Work Environment', 'workspace', 'Describes workspace nature'),
('command_center', 'مركز القيادة', 'Command Center', 'workspace', 'Describes dashboard nature'),
('productive_collaboration', 'التعاون الإنتاجي', 'Productive Collaboration', 'workspace', 'Workspace collaboration focus'),
('passive_monitoring', 'المراقبة السلبية', 'Passive Monitoring', 'workspace', 'Dashboard monitoring nature'),

-- User Workspace Translations
('personal_innovation_journey', 'رحلة الابتكار الشخصية', 'Personal Innovation Journey', 'workspace', 'User workspace main purpose'),
('idea_development_tools', 'أدوات تطوير الأفكار', 'Idea Development Tools', 'workspace', 'User workspace feature'),
('challenge_participation', 'المشاركة في التحديات', 'Challenge Participation', 'workspace', 'User workspace feature'),
('learning_resources', 'موارد التعلم', 'Learning Resources', 'workspace', 'User workspace feature'),
('personal_analytics', 'التحليلات الشخصية', 'Personal Analytics', 'workspace', 'User workspace feature'),
('innovation_guides', 'أدلة الابتكار', 'Innovation Guides', 'workspace', 'User workspace learning materials'),
('idea_success_rate', 'معدل نجاح الأفكار', 'Idea Success Rate', 'workspace', 'User analytics metric'),
('evaluation_feedback', 'ملاحظات التقييم', 'Evaluation Feedback', 'workspace', 'User analytics component'),
('innovation_groups', 'مجموعات الابتكار', 'Innovation Groups', 'workspace', 'User collaboration feature'),
('personal_portfolio', 'المحفظة الشخصية', 'Personal Portfolio', 'workspace', 'User document management'),

-- Expert Workspace Translations  
('evaluation_management_system', 'نظام إدارة التقييم', 'Evaluation Management System', 'workspace', 'Expert workspace main purpose'),
('assessment_tools', 'أدوات التقييم', 'Assessment Tools', 'workspace', 'Expert workspace feature'),
('review_queue', 'قائمة انتظار المراجعة', 'Review Queue', 'workspace', 'Expert workspace feature'),
('expert_resources', 'موارد الخبراء', 'Expert Resources', 'workspace', 'Expert workspace feature'),
('expert_panels', 'لجان الخبراء', 'Expert Panels', 'workspace', 'Expert collaboration feature'),
('evaluation_guidelines', 'إرشادات التقييم', 'Evaluation Guidelines', 'workspace', 'Expert resource type'),
('domain_expertise_materials', 'مواد الخبرة المجالية', 'Domain Expertise Materials', 'workspace', 'Expert resource type'),
('comparative_analysis', 'التحليل المقارن', 'Comparative Analysis', 'workspace', 'Expert assessment tool'),
('evaluation_quality', 'جودة التقييم', 'Evaluation Quality', 'workspace', 'Expert performance metric'),
('consistency_metrics', 'مقاييس الاتساق', 'Consistency Metrics', 'workspace', 'Expert performance tracking'),
('peer_discussions', 'مناقشات الأقران', 'Peer Discussions', 'workspace', 'Expert collaboration'),
('industry_insights', 'رؤى الصناعة', 'Industry Insights', 'workspace', 'Expert knowledge resource'),

-- Organization Workspace Translations
('innovation_program_management', 'إدارة برامج الابتكار', 'Innovation Program Management', 'workspace', 'Organization workspace main purpose'),
('challenge_creation_management', 'إنشاء وإدارة التحديات', 'Challenge Creation & Management', 'workspace', 'Organization workspace feature'),
('team_coordination', 'تنسيق الفريق', 'Team Coordination', 'workspace', 'Organization workspace feature'),
('resource_planning', 'تخطيط الموارد', 'Resource Planning', 'workspace', 'Organization workspace feature'),
('stakeholder_communication', 'التواصل مع أصحاب المصلحة', 'Stakeholder Communication', 'workspace', 'Organization workspace feature'),
('innovation_pipeline', 'خط أنابيب الابتكار', 'Innovation Pipeline', 'workspace', 'Organization workspace feature'),
('impact_measurement', 'قياس التأثير', 'Impact Measurement', 'workspace', 'Organization workspace feature'),
('cross_department_collaboration', 'التعاون بين الأقسام', 'Cross-Department Collaboration', 'workspace', 'Organization collaboration'),
('budget_allocation', 'تخصيص الميزانية', 'Budget Allocation', 'workspace', 'Organization planning tool'),
('timeline_management', 'إدارة الجدول الزمني', 'Timeline Management', 'workspace', 'Organization planning tool'),
('approval_workflows', 'سير عمل الموافقات', 'Approval Workflows', 'workspace', 'Organization process'),
('feedback_loops', 'حلقات التغذية الراجعة', 'Feedback Loops', 'workspace', 'Organization communication'),
('roi_tracking', 'تتبع العائد على الاستثمار', 'ROI Tracking', 'workspace', 'Organization measurement'),
('success_metrics', 'مقاييس النجاح', 'Success Metrics', 'workspace', 'Organization measurement'),

-- Partner Workspace Translations
('marketplace_management', 'إدارة السوق', 'Marketplace Management', 'workspace', 'Partner workspace main purpose'),
('partnership_hub', 'مركز الشراكة', 'Partnership Hub', 'workspace', 'Partner workspace feature'),
('business_development', 'تطوير الأعمال', 'Business Development', 'workspace', 'Partner workspace feature'),
('service_delivery', 'تقديم الخدمات', 'Service Delivery', 'workspace', 'Partner workspace feature'),
('revenue_analytics', 'تحليلات الإيرادات', 'Revenue Analytics', 'workspace', 'Partner workspace feature'),
('relationship_management', 'إدارة العلاقات', 'Relationship Management', 'workspace', 'Partner workspace feature'),
('resource_sharing', 'مشاركة الموارد', 'Resource Sharing', 'workspace', 'Partner workspace feature'),
('joint_ventures', 'المشاريع المشتركة', 'Joint Ventures', 'workspace', 'Partner collaboration'),
('lead_tracking', 'تتبع العملاء المحتملين', 'Lead Tracking', 'workspace', 'Partner business tool'),
('proposal_management', 'إدارة المقترحات', 'Proposal Management', 'workspace', 'Partner business tool'),
('project_execution', 'تنفيذ المشاريع', 'Project Execution', 'workspace', 'Partner delivery tool'),
('client_communication', 'التواصل مع العملاء', 'Client Communication', 'workspace', 'Partner delivery tool'),
('financial_tracking', 'التتبع المالي', 'Financial Tracking', 'workspace', 'Partner analytics'),
('client_portfolios', 'محافظ العملاء', 'Client Portfolios', 'workspace', 'Partner relationship tool'),
('satisfaction_tracking', 'تتبع الرضا', 'Satisfaction Tracking', 'workspace', 'Partner relationship metric'),
('knowledge_exchange', 'تبادل المعرفة', 'Knowledge Exchange', 'workspace', 'Partner resource sharing'),
('co_innovation', 'الابتكار المشترك', 'Co-Innovation', 'workspace', 'Partner collaboration model'),

-- Admin Workspace Translations
('system_administration', 'إدارة النظام', 'System Administration', 'workspace', 'Admin workspace main purpose'),
('content_moderation', 'إشراف المحتوى', 'Content Moderation', 'workspace', 'Admin workspace feature'),
('analytics_deep_dive', 'التحليل العميق', 'Analytics Deep Dive', 'workspace', 'Admin workspace feature'),
('security_management', 'إدارة الأمان', 'Security Management', 'workspace', 'Admin workspace feature'),
('support_operations', 'عمليات الدعم', 'Support Operations', 'workspace', 'Admin workspace feature'),
('platform_evolution', 'تطوير المنصة', 'Platform Evolution', 'workspace', 'Admin workspace feature'),
('platform_configuration', 'تكوين المنصة', 'Platform Configuration', 'workspace', 'Admin system tool'),
('quality_control', 'مراقبة الجودة', 'Quality Control', 'workspace', 'Admin moderation tool'),
('performance_optimization', 'تحسين الأداء', 'Performance Optimization', 'workspace', 'Admin analytics tool'),
('access_control', 'التحكم في الوصول', 'Access Control', 'workspace', 'Admin security tool'),
('audit_trails', 'مسارات التدقيق', 'Audit Trails', 'workspace', 'Admin security feature'),
('ticket_management', 'إدارة التذاكر', 'Ticket Management', 'workspace', 'Admin support tool'),
('user_assistance', 'مساعدة المستخدمين', 'User Assistance', 'workspace', 'Admin support feature'),
('feature_planning', 'تخطيط الميزات', 'Feature Planning', 'workspace', 'Admin evolution tool'),
('feedback_analysis', 'تحليل التغذية الراجعة', 'Feedback Analysis', 'workspace', 'Admin evolution process'),

-- Team Workspace Translations
('collaborative_project_environment', 'بيئة المشاريع التعاونية', 'Collaborative Project Environment', 'workspace', 'Team workspace main purpose'),
('shared_documents', 'المستندات المشتركة', 'Shared Documents', 'workspace', 'Team workspace feature'),
('task_management', 'إدارة المهام', 'Task Management', 'workspace', 'Team workspace feature'),
('communication_hub', 'مركز التواصل', 'Communication Hub', 'workspace', 'Team workspace feature'),
('meeting_management', 'إدارة الاجتماعات', 'Meeting Management', 'workspace', 'Team workspace feature'),
('workflow_automation', 'أتمتة سير العمل', 'Workflow Automation', 'workspace', 'Team workspace feature'),
('real_time_editing', 'التحرير في الوقت الفعلي', 'Real-Time Editing', 'workspace', 'Team collaboration tool'),
('version_control', 'التحكم في الإصدارات', 'Version Control', 'workspace', 'Team document feature'),
('progress_tracking', 'تتبع التقدم', 'Progress Tracking', 'workspace', 'Team task feature'),
('team_chat', 'دردشة الفريق', 'Team Chat', 'workspace', 'Team communication tool'),
('video_calls', 'مكالمات الفيديو', 'Video Calls', 'workspace', 'Team communication tool'),
('announcements', 'الإعلانات', 'Announcements', 'workspace', 'Team communication feature'),
('file_repositories', 'مستودعات الملفات', 'File Repositories', 'workspace', 'Team resource tool'),
('knowledge_bases', 'قواعد المعرفة', 'Knowledge Bases', 'workspace', 'Team resource feature'),
('meeting_agendas', 'جداول أعمال الاجتماعات', 'Meeting Agendas', 'workspace', 'Team meeting tool'),
('meeting_minutes', 'محاضر الاجتماعات', 'Meeting Minutes', 'workspace', 'Team meeting feature'),
('process_templates', 'قوالب العمليات', 'Process Templates', 'workspace', 'Team automation tool'),
('approval_chains', 'سلاسل الموافقة', 'Approval Chains', 'workspace', 'Team workflow feature'),

-- Workspace Navigation & UI
('workspace_navigation', 'تنقل مساحة العمل', 'Workspace Navigation', 'workspace', 'UI navigation'),
('switch_workspace', 'تبديل مساحة العمل', 'Switch Workspace', 'workspace', 'UI action'),
('workspace_settings', 'إعدادات مساحة العمل', 'Workspace Settings', 'workspace', 'UI feature'),
('workspace_overview', 'نظرة عامة على مساحة العمل', 'Workspace Overview', 'workspace', 'UI section'),
('recent_activity', 'النشاط الحديث', 'Recent Activity', 'workspace', 'UI component'),
('quick_actions', 'الإجراءات السريعة', 'Quick Actions', 'workspace', 'UI component'),
('workspace_search', 'البحث في مساحة العمل', 'Workspace Search', 'workspace', 'UI feature'),
('workspace_notifications', 'إشعارات مساحة العمل', 'Workspace Notifications', 'workspace', 'UI feature'),

-- Workspace Management
('create_workspace', 'إنشاء مساحة عمل', 'Create Workspace', 'workspace', 'Management action'),
('manage_workspace', 'إدارة مساحة العمل', 'Manage Workspace', 'workspace', 'Management action'),
('workspace_permissions', 'أذونات مساحة العمل', 'Workspace Permissions', 'workspace', 'Management feature'),
('workspace_members', 'أعضاء مساحة العمل', 'Workspace Members', 'workspace', 'Management component'),
('invite_to_workspace', 'دعوة إلى مساحة العمل', 'Invite to Workspace', 'workspace', 'Management action'),
('workspace_admin', 'مدير مساحة العمل', 'Workspace Admin', 'workspace', 'Management role'),

-- Performance & Analytics
('workspace_productivity', 'إنتاجية مساحة العمل', 'Workspace Productivity', 'workspace', 'Analytics metric'),
('collaboration_metrics', 'مقاييس التعاون', 'Collaboration Metrics', 'workspace', 'Analytics component'),
('workspace_usage', 'استخدام مساحة العمل', 'Workspace Usage', 'workspace', 'Analytics data'),
('active_collaborators', 'المتعاونون النشطون', 'Active Collaborators', 'workspace', 'Analytics metric'),
('completed_tasks', 'المهام المكتملة', 'Completed Tasks', 'workspace', 'Analytics metric'),
('workspace_efficiency', 'كفاءة مساحة العمل', 'Workspace Efficiency', 'workspace', 'Analytics measure');