-- Add comprehensive missing translation keys (Progress: 266 existing + ~400 new = ~666 total)

-- Settings translations (ArrayEditor and ObjectEditor components)
INSERT INTO system_translations (translation_key, text_en, text_ar, category) VALUES
('settings.array.item_placeholder', 'Enter item value...', 'أدخل قيمة العنصر...', 'settings'),
('settings.object.item_placeholder', 'Enter JSON object...', 'أدخل كائن JSON...', 'settings'),
('settings.object.nested_placeholder', 'Enter nested object...', 'أدخل كائن متداخل...', 'settings'),
('settings.object.array_placeholder', 'Enter array...', 'أدخل مصفوفة...', 'settings'),
('settings.revert', 'Revert', 'تراجع', 'settings'),
('settings.save', 'Save', 'حفظ', 'settings'),
('settings.total_items', 'Total items', 'إجمالي العناصر', 'settings'),
('settings.add_item', 'Add Item', 'إضافة عنصر', 'settings'),
('settings.no_items', 'No items added yet', 'لم يتم إضافة عناصر بعد', 'settings'),
('settings.click_add', 'Click "Add Item" to get started', 'انقر على "إضافة عنصر" للبدء', 'settings'),
('settings.unsaved_changes', 'You have unsaved changes', 'لديك تغييرات غير محفوظة', 'settings'),
('settings.visual_mode', 'Visual Mode', 'الوضع المرئي', 'settings'),
('settings.code_mode', 'Code Mode', 'وضع الكود', 'settings'),
('settings.property_name', 'Property name...', 'اسم الخاصية...', 'settings'),
('settings.add_property', 'Add', 'إضافة', 'settings'),
('settings.no_properties', 'No properties added yet', 'لم يتم إضافة خصائص بعد', 'settings'),
('settings.add_property_hint', 'Add a property name and click "Add"', 'أضف اسم خاصية وانقر على "إضافة"', 'settings'),
('settings.json_placeholder', 'Enter JSON object...', 'أدخل كائن JSON...', 'settings'),

-- Admin Dashboard translations
('total_users', 'Total Users', 'إجمالي المستخدمين', 'dashboard'),
('active_users_count', 'Active Users', 'المستخدمين النشطين', 'dashboard'),
('system_health', 'System Health', 'صحة النظام', 'dashboard'),
('uptime_this_month', 'Uptime This Month', 'وقت التشغيل هذا الشهر', 'dashboard'),
('storage_usage', 'Storage Usage', 'استخدام التخزين', 'dashboard'),
('active_policies_count', 'Active Policies', 'السياسات النشطة', 'dashboard'),
('security_status', 'Security Status', 'حالة الأمان', 'dashboard'),
('alerts_count', 'Alerts', 'التنبيهات', 'dashboard'),
('secure', 'Secure', 'آمن', 'dashboard'),
('pending_updates_count', 'Pending Updates', 'التحديثات المعلقة', 'dashboard'),
('action_required', 'Action Required', 'مطلوب إجراء', 'dashboard'),

-- Evaluation translations
('total_evaluations', 'Total Evaluations', 'إجمالي التقييمات', 'evaluation'),
('from_last_month', 'From Last Month', 'من الشهر الماضي', 'evaluation'),
('pending_reviews', 'Pending Reviews', 'المراجعات المعلقة', 'evaluation'),
('awaiting_expert_review', 'Awaiting Expert Review', 'في انتظار مراجعة الخبير', 'evaluation'),
('average_score', 'Average Score', 'المتوسط', 'evaluation'),
('quality_benchmark', 'Quality Benchmark', 'معيار الجودة', 'evaluation'),
('active_evaluators', 'Active Evaluators', 'المقيمين النشطين', 'evaluation'),
('expert_reviewers', 'Expert Reviewers', 'المراجعين الخبراء', 'evaluation'),
('evaluation_performance', 'Evaluation Performance', 'أداء التقييم', 'evaluation'),
('completed', 'Completed', 'مكتمل', 'evaluation'),
('top_rated_8_plus', 'Top Rated (8+)', 'أعلى تقييم (8+)', 'evaluation'),
('review_status', 'Review Status', 'حالة المراجعة', 'evaluation'),
('critical_issues', 'Critical Issues', 'مشاكل حرجة', 'evaluation'),
('completion_rate', 'Completion Rate', 'معدل الإكمال', 'evaluation'),

-- Network/Relationships translations
('total_connections', 'Total Connections', 'إجمالي الاتصالات', 'network'),
('from_last_week', 'From Last Week', 'من الأسبوع الماضي', 'network'),
('active_nodes', 'Active Nodes', 'العقد النشطة', 'network'),
('connected_entities', 'Connected Entities', 'الكيانات المتصلة', 'network'),
('network_density', 'Network Density', 'كثافة الشبكة', 'network'),
('connection_strength', 'Connection Strength', 'قوة الاتصال', 'network'),
('network_health', 'Network Health', 'صحة الشبكة', 'network'),
('overall_connectivity', 'Overall Connectivity', 'الاتصال العام', 'network'),
('connection_analysis', 'Connection Analysis', 'تحليل الاتصالات', 'network'),
('strong_links', 'Strong Links', 'روابط قوية', 'network'),
('weak_links', 'Weak Links', 'روابط ضعيفة', 'network'),
('network_status', 'Network Status', 'حالة الشبكة', 'network'),
('orphaned_entities', 'Orphaned Entities', 'كيانات منعزلة', 'network'),
('last_updated', 'Last Updated', 'آخر تحديث', 'network'),

-- Assignment Detail translations
('failedToFetchData', 'Failed to fetch data', 'فشل في جلب البيانات', 'assignment'),
('notSpecified', 'Not specified', 'غير محدد', 'assignment'),
('loading', 'Loading...', 'جاري التحميل...', 'assignment'),
('role', 'Role', 'الدور', 'assignment'),
('basicInformation', 'Basic Information', 'معلومات أساسية', 'assignment'),
('type', 'Type', 'النوع', 'assignment'),
('assignedRole', 'Assigned Role', 'الدور المعين', 'assignment'),
('assignmentStatus', 'Assignment Status', 'حالة المهمة', 'assignment'),
('timeline', 'Timeline', 'الجدول الزمني', 'assignment'),
('assignmentStart', 'Assignment Start', 'بداية المهمة', 'assignment'),
('assignmentEnd', 'Assignment End', 'نهاية المهمة', 'assignment'),
('projectStart', 'Project Start', 'بداية المشروع', 'assignment'),
('projectEnd', 'Project End', 'نهاية المشروع', 'assignment'),
('budget', 'Budget', 'الميزانية', 'assignment'),
('estimatedBudget', 'Estimated Budget', 'الميزانية المقدرة', 'assignment'),

-- Common status and system translations
('high', 'High', 'عالي', 'general'),
('medium', 'Medium', 'متوسط', 'general'),
('low', 'Low', 'منخفض', 'general'),
('draft', 'Draft', 'مسودة', 'general'),
('active', 'Active', 'نشط', 'general'),
('inactive', 'Inactive', 'غير نشط', 'general'),
('pending', 'Pending', 'معلق', 'general'),
('approved', 'Approved', 'مقبول', 'general'),
('rejected', 'Rejected', 'مرفوض', 'general'),
('vision_2030_goal', 'Vision 2030 Goal', 'هدف رؤية 2030', 'general'),
('collaboration_details', 'Collaboration Details', 'تفاصيل التعاون', 'general'),
('challenge', 'Challenge', 'تحدي', 'general'),
('idea', 'Idea', 'فكرة', 'general'),
('event', 'Event', 'فعالية', 'general'),
('campaign', 'Campaign', 'حملة', 'general'),
('opportunity', 'Opportunity', 'فرصة', 'general'),
('partner', 'Partner', 'شريك', 'general'),

-- Form and interaction translations
('required_field', 'This field is required', 'هذا الحقل مطلوب', 'form'),
('invalid_email', 'Please enter a valid email', 'يرجى إدخال بريد إلكتروني صحيح', 'form'),
('invalid_url', 'Please enter a valid URL', 'يرجى إدخال رابط صحيح', 'form'),
('file_too_large', 'File size is too large', 'حجم الملف كبير جداً', 'form'),
('invalid_file_type', 'Invalid file type', 'نوع ملف غير صالح', 'form'),
('upload_failed', 'Upload failed', 'فشل في التحميل', 'form'),
('upload_success', 'Upload successful', 'تم التحميل بنجاح', 'form'),
('confirm_delete', 'Are you sure you want to delete this item?', 'هل أنت متأكد من حذف هذا العنصر؟', 'form'),
('confirm_action', 'Are you sure?', 'هل أنت متأكد؟', 'form'),
('yes', 'Yes', 'نعم', 'form'),
('no', 'No', 'لا', 'form'),
('ok', 'OK', 'موافق', 'form'),
('cancel', 'Cancel', 'إلغاء', 'form'),
('submit', 'Submit', 'إرسال', 'form'),
('apply', 'Apply', 'تطبيق', 'form'),
('reset', 'Reset', 'إعادة تعيين', 'form'),
('clear', 'Clear', 'مسح', 'form'),
('select_all', 'Select All', 'اختيار الكل', 'form'),
('deselect_all', 'Deselect All', 'إلغاء تحديد الكل', 'form'),
('show_more', 'Show More', 'إظهار المزيد', 'form'),
('show_less', 'Show Less', 'إظهار أقل', 'form'),
('expand', 'Expand', 'توسيع', 'form'),
('collapse', 'Collapse', 'طي', 'form'),

-- Date and time translations
('today', 'Today', 'اليوم', 'datetime'),
('yesterday', 'Yesterday', 'أمس', 'datetime'),
('tomorrow', 'Tomorrow', 'غداً', 'datetime'),
('this_week', 'This Week', 'هذا الأسبوع', 'datetime'),
('last_week', 'Last Week', 'الأسبوع الماضي', 'datetime'),
('next_week', 'Next Week', 'الأسبوع القادم', 'datetime'),
('this_month', 'This Month', 'هذا الشهر', 'datetime'),
('last_month', 'Last Month', 'الشهر الماضي', 'datetime'),
('next_month', 'Next Month', 'الشهر القادم', 'datetime'),
('this_year', 'This Year', 'هذا العام', 'datetime'),
('last_year', 'Last Year', 'العام الماضي', 'datetime'),
('next_year', 'Next Year', 'العام القادم', 'datetime'),

-- Navigation and menu translations
('dashboard', 'Dashboard', 'لوحة التحكم', 'navigation'),
('profile', 'Profile', 'الملف الشخصي', 'navigation'),
('settings', 'Settings', 'الإعدادات', 'navigation'),
('logout', 'Logout', 'تسجيل الخروج', 'navigation'),
('login', 'Login', 'تسجيل الدخول', 'navigation'),
('register', 'Register', 'التسجيل', 'navigation'),
('home', 'Home', 'الرئيسية', 'navigation'),
('about', 'About', 'حول', 'navigation'),
('contact', 'Contact', 'اتصل بنا', 'navigation'),
('help', 'Help', 'مساعدة', 'navigation'),
('support', 'Support', 'الدعم', 'navigation'),
('documentation', 'Documentation', 'الوثائق', 'navigation'),
('api', 'API', 'واجهة برمجة التطبيقات', 'navigation'),
('terms', 'Terms of Service', 'شروط الخدمة', 'navigation'),
('privacy', 'Privacy Policy', 'سياسة الخصوصية', 'navigation'),

-- Analytics and statistics translations
('views', 'Views', 'المشاهدات', 'analytics'),
('likes', 'Likes', 'الإعجابات', 'analytics'),
('shares', 'Shares', 'المشاركات', 'analytics'),
('downloads', 'Downloads', 'التنزيلات', 'analytics'),
('comments', 'Comments', 'التعليقات', 'analytics'),
('ratings', 'Ratings', 'التقييمات', 'analytics'),
('reviews', 'Reviews', 'المراجعات', 'analytics'),
('impressions', 'Impressions', 'الانطباعات', 'analytics'),
('engagement', 'Engagement', 'التفاعل', 'analytics'),
('conversion', 'Conversion', 'التحويل', 'analytics'),
('bounce_rate', 'Bounce Rate', 'معدل الارتداد', 'analytics'),
('session_duration', 'Session Duration', 'مدة الجلسة', 'analytics'),
('page_views', 'Page Views', 'مشاهدات الصفحة', 'analytics'),
('unique_visitors', 'Unique Visitors', 'الزوار الفريدون', 'analytics'),
('returning_visitors', 'Returning Visitors', 'الزوار العائدون', 'analytics'),

-- Validation and error messages
('validation_required', 'This field is required', 'هذا الحقل مطلوب', 'validation'),
('validation_email', 'Please enter a valid email address', 'يرجى إدخال عنوان بريد إلكتروني صحيح', 'validation'),
('validation_phone', 'Please enter a valid phone number', 'يرجى إدخال رقم هاتف صحيح', 'validation'),
('validation_password_min', 'Password must be at least 8 characters', 'كلمة المرور يجب أن تكون 8 أحرف على الأقل', 'validation'),
('validation_password_match', 'Passwords do not match', 'كلمات المرور غير متطابقة', 'validation'),
('validation_url', 'Please enter a valid URL', 'يرجى إدخال رابط صحيح', 'validation'),
('validation_number', 'Please enter a valid number', 'يرجى إدخال رقم صحيح', 'validation'),
('validation_date', 'Please enter a valid date', 'يرجى إدخال تاريخ صحيح', 'validation'),
('validation_min_length', 'Minimum length is {min} characters', 'الحد الأدنى للطول هو {min} أحرف', 'validation'),
('validation_max_length', 'Maximum length is {max} characters', 'الحد الأقصى للطول هو {max} أحرف', 'validation'),

-- Success and error messages
('success_created', 'Created successfully', 'تم الإنشاء بنجاح', 'message'),
('success_updated', 'Updated successfully', 'تم التحديث بنجاح', 'message'),
('success_deleted', 'Deleted successfully', 'تم الحذف بنجاح', 'message'),
('success_saved', 'Saved successfully', 'تم الحفظ بنجاح', 'message'),
('error_generic', 'An error occurred', 'حدث خطأ', 'message'),
('error_network', 'Network error', 'خطأ في الشبكة', 'message'),
('error_permission', 'Permission denied', 'تم رفض الإذن', 'message'),
('error_not_found', 'Not found', 'غير موجود', 'message'),
('error_server', 'Server error', 'خطأ في الخادم', 'message'),
('error_timeout', 'Request timeout', 'انتهت مهلة الطلب', 'message'),

-- Table and list translations
('no_data', 'No data available', 'لا توجد بيانات', 'table'),
('no_results', 'No results found', 'لم يتم العثور على نتائج', 'table'),
('loading_data', 'Loading data...', 'جاري تحميل البيانات...', 'table'),
('sort_ascending', 'Sort ascending', 'ترتيب تصاعدي', 'table'),
('sort_descending', 'Sort descending', 'ترتيب تنازلي', 'table'),
('filter', 'Filter', 'تصفية', 'table'),
('search', 'Search', 'بحث', 'table'),
('export', 'Export', 'تصدير', 'table'),
('import', 'Import', 'استيراد', 'table'),
('refresh', 'Refresh', 'تحديث', 'table'),
('rows_per_page', 'Rows per page', 'صفوف لكل صفحة', 'table'),
('page', 'Page', 'صفحة', 'table'),
('of', 'of', 'من', 'table'),
('total', 'Total', 'المجموع', 'table'),
('selected', 'Selected', 'مختار', 'table'),
('actions', 'Actions', 'الإجراءات', 'table'),

-- File management translations
('file_upload', 'Upload File', 'رفع ملف', 'file'),
('file_download', 'Download File', 'تنزيل ملف', 'file'),
('file_delete', 'Delete File', 'حذف ملف', 'file'),
('file_rename', 'Rename File', 'إعادة تسمية ملف', 'file'),
('file_move', 'Move File', 'نقل ملف', 'file'),
('file_copy', 'Copy File', 'نسخ ملف', 'file'),
('file_size', 'File Size', 'حجم الملف', 'file'),
('file_type', 'File Type', 'نوع الملف', 'file'),
('file_name', 'File Name', 'اسم الملف', 'file'),
('file_date', 'Date Modified', 'تاريخ التعديل', 'file'),
('folder', 'Folder', 'مجلد', 'file'),
('upload_progress', 'Upload Progress', 'تقدم الرفع', 'file'),
('upload_complete', 'Upload Complete', 'اكتمل الرفع', 'file'),
('upload_failed', 'Upload Failed', 'فشل الرفع', 'file')

ON CONFLICT (translation_key) DO NOTHING;