-- Insert remaining toast message translations
INSERT INTO system_translations (translation_key, text_en, text_ar, category) VALUES
-- Toast messages
('toast.fill_required_fields', 'Please fill in all required fields', 'يرجى ملء جميع الحقول المطلوبة', 'validation'),
('toast.login_required', 'You must be logged in to request a role', 'يجب تسجيل الدخول لطلب دور', 'authentication'),
('toast.role_already_assigned', 'You already have this role assigned', 'لديك هذا الدور مُعين بالفعل', 'role_management'),
('toast.dashboard_error', 'Error loading dashboard data', 'خطأ في تحميل بيانات لوحة القيادة', 'error'),
('toast.organization_error', 'Error loading organization data', 'خطأ في تحميل بيانات المنظمة', 'error'),
('toast.avatar_updated', 'Avatar updated successfully!', 'تم تحديث الصورة الشخصية بنجاح!', 'success'),
('toast.avatar_upload_error', 'Error uploading avatar. Please try again.', 'خطأ في تحميل الصورة الشخصية. يرجى المحاولة مرة أخرى.', 'error'),
('toast.select_image_file', 'Please select an image file', 'يرجى اختيار ملف صورة', 'validation'),
('toast.file_size_limit', 'File size must be less than 5MB', 'يجب أن يكون حجم الملف أقل من 5 ميجابايت', 'validation'),
('toast.avatar_removed', 'Avatar removed', 'تمت إزالة الصورة الشخصية', 'success'),
('toast.avatar_remove_error', 'Error removing avatar', 'خطأ في إزالة الصورة الشخصية', 'error'),
('toast.image_search_failed', 'Failed to search images', 'فشل في البحث عن الصور', 'error'),
('toast.expert_dashboard_error', 'Error loading expert dashboard data', 'خطأ في تحميل بيانات لوحة القيادة للخبير', 'error'),
('toast.expert_profile_error', 'Error loading expert profile', 'خطأ في تحميل ملف الخبير الشخصي', 'error'),
('toast.expert_profile_saved', 'Expert profile saved successfully!', 'تم حفظ ملف الخبير الشخصي بنجاح!', 'success'),
('toast.expert_profile_save_error', 'Error saving expert profile', 'خطأ في حفظ ملف الخبير الشخصي', 'error'),
('toast.drafts_load_error', 'Failed to load drafts', 'فشل في تحميل المسودات', 'error'),
('toast.draft_deleted', 'Draft deleted successfully', 'تم حذف المسودة بنجاح', 'success'),
('toast.draft_delete_error', 'Failed to delete draft', 'فشل في حذف المسودة', 'error'),
('toast.challenges_load_error', 'Error loading challenges and focus questions', 'خطأ في تحميل التحديات والأسئلة المحورية', 'error'),
('toast.draft_auto_saved', 'Draft auto-saved', 'تم حفظ المسودة تلقائياً', 'success'),
('toast.draft_loaded', 'Draft loaded successfully', 'تم تحميل المسودة بنجاح', 'success'),
('toast.draft_load_error', 'Error loading draft', 'خطأ في تحميل المسودة', 'error'),
('toast.draft_saved_manually', 'Draft saved manually', 'تم حفظ المسودة يدوياً', 'success'),
('toast.user_not_authenticated', 'User not authenticated', 'المستخدم غير مسجل الدخول', 'authentication'),
('toast.idea_submitted', 'Idea submitted successfully!', 'تم إرسال الفكرة بنجاح!', 'success'),
('toast.idea_submit_error', 'Error submitting idea. Please try again.', 'خطأ في إرسال الفكرة. يرجى المحاولة مرة أخرى.', 'error'),
('toast.partner_data_error', 'Error loading partner data, showing demo content', 'خطأ في تحميل بيانات الشريك، عرض محتوى تجريبي', 'error'),
('toast.partner_profile_error', 'Error loading partner profile', 'خطأ في تحميل ملف الشريك الشخصي', 'error'),
('toast.partner_profile_saved', 'Partner profile saved successfully!', 'تم حفظ ملف الشريك الشخصي بنجاح!', 'success'),
('toast.partner_profile_save_error', 'Error saving partner profile', 'خطأ في حفظ ملف الشريك الشخصي', 'error'),
('toast.statistics_exported', 'Statistics exported successfully', 'تم تصدير الإحصائيات بنجاح', 'success'),
('toast.statistics_export_error', 'Failed to export statistics', 'فشل في تصدير الإحصائيات', 'error'),

-- Advanced Search options
('status.draft', 'Draft', 'مسودة', 'status'),
('status.active', 'Active', 'نشط', 'status'),
('status.completed', 'Completed', 'مكتمل', 'status'),
('status.cancelled', 'Cancelled', 'ملغي', 'status'),
('status.submitted', 'Submitted', 'مقدم', 'status'),
('status.under_review', 'Under Review', 'قيد المراجعة', 'status'),
('status.approved', 'Approved', 'معتمد', 'status'),
('status.rejected', 'Rejected', 'مرفوض', 'status'),
('status.upcoming', 'Upcoming', 'قادم', 'status'),
('status.registration_open', 'Registration Open', 'التسجيل مفتوح', 'status'),
('status.registration_closed', 'Registration Closed', 'التسجيل مغلق', 'status'),
('status.ongoing', 'Ongoing', 'جاري', 'status'),
('status.open', 'Open', 'مفتوح', 'status'),
('status.closed', 'Closed', 'مغلق', 'status'),
('status.paused', 'Paused', 'متوقف مؤقتاً', 'status')

ON CONFLICT (translation_key) DO UPDATE SET
  text_en = EXCLUDED.text_en,
  text_ar = EXCLUDED.text_ar,
  category = EXCLUDED.category,
  updated_at = now();