-- Add translation keys for AdvancedSearch and ChallengeForm components
INSERT INTO system_translations (translation_key, text_en, text_ar, category) VALUES
-- AdvancedSearch component translations
('advanced_search.title', 'Advanced Search', 'البحث المتقدم', 'ui'),
('advanced_search.filters_active', 'filters active', 'مرشحات نشطة', 'ui'),
('ui.less', 'Less', 'أقل', 'ui'),
('ui.more', 'More', 'المزيد', 'ui'),
('advanced_search.search_query', 'Search Query', 'استعلام البحث', 'ui'),
('advanced_search.search_placeholder', 'Search for challenges, ideas, or events...', 'البحث عن التحديات والأفكار أو الأحداث...', 'ui'),
('advanced_search.status', 'Status', 'الحالة', 'ui'),
('advanced_search.select_status', 'Select status', 'اختر الحالة', 'ui'),
('advanced_search.all_statuses', 'All Statuses', 'جميع الحالات', 'ui'),
('advanced_search.priority', 'Priority', 'الأولوية', 'ui'),
('advanced_search.select_priority', 'Select priority', 'اختر الأولوية', 'ui'),
('advanced_search.all_priorities', 'All Priorities', 'جميع الأولويات', 'ui'),
('advanced_search.date_range', 'Date Range', 'نطاق التاريخ', 'ui'),
('advanced_search.start_date', 'Start Date', 'تاريخ البداية', 'ui'),
('advanced_search.end_date', 'End Date', 'تاريخ النهاية', 'ui'),
('advanced_search.budget_range', 'Budget Range', 'نطاق الميزانية', 'ui'),
('advanced_search.minimum_budget', 'Minimum Budget', 'الحد الأدنى للميزانية', 'ui'),
('advanced_search.maximum_budget', 'Maximum Budget', 'الحد الأقصى للميزانية', 'ui'),
('advanced_search.tags', 'Tags', 'العلامات', 'ui'),
('advanced_search.tag_selector_coming_soon', 'Tag selector coming soon...', 'محدد العلامات قريباً...', 'ui'),
('advanced_search.search', 'Search', 'بحث', 'ui'),
('advanced_search.clear_filters', 'Clear Filters', 'مسح المرشحات', 'ui'),

-- ChallengeForm component translations
('challenge_form.create_challenge', 'Create Challenge', 'إنشاء تحدٍ', 'forms'),
('challenge_form.edit_challenge', 'Edit Challenge', 'تعديل التحدي', 'forms'),
('challenge_form.create_challenge_description', 'Create a new challenge to engage innovators and drive solutions.', 'أنشئ تحدياً جديداً لإشراك المبتكرين وقيادة الحلول.', 'forms'),
('challenge_form.edit_challenge_description', 'Update the challenge details and requirements.', 'تحديث تفاصيل التحدي والمتطلبات.', 'forms'),
('challenge_form.challenge_title', 'Challenge Title', 'عنوان التحدي', 'forms'),
('challenge_form.challenge_title_placeholder', 'Enter the challenge title in Arabic', 'أدخل عنوان التحدي باللغة العربية', 'forms'),
('challenge_form.challenge_title_en', 'Challenge Title (English)', 'عنوان التحدي (الإنجليزية)', 'forms'),
('challenge_form.challenge_title_en_placeholder', 'Enter the challenge title in English', 'أدخل عنوان التحدي باللغة الإنجليزية', 'forms'),
('challenge_form.challenge_description', 'Challenge Description', 'وصف التحدي', 'forms'),
('challenge_form.challenge_description_placeholder', 'Describe the challenge, its objectives, and expected outcomes', 'صف التحدي وأهدافه والنتائج المتوقعة', 'forms'),
('challenge_form.challenge_description_en', 'Challenge Description (English)', 'وصف التحدي (الإنجليزية)', 'forms'),
('challenge_form.challenge_description_en_placeholder', 'Describe the challenge in English', 'صف التحدي باللغة الإنجليزية', 'forms'),
('challenge_form.challenge_type', 'Challenge Type', 'نوع التحدي', 'forms'),
('challenge_form.select_challenge_type', 'Select challenge type', 'اختر نوع التحدي', 'forms'),
('challenge_form.priority_level', 'Priority Level', 'مستوى الأولوية', 'forms'),
('challenge_form.select_priority', 'Select priority level', 'اختر مستوى الأولوية', 'forms'),
('challenge_form.estimated_budget', 'Estimated Budget', 'الميزانية المقدرة', 'forms'),
('challenge_form.budget_placeholder', 'Enter budget in SAR', 'أدخل الميزانية بالريال السعودي', 'forms'),
('challenge_form.start_date', 'Start Date', 'تاريخ البداية', 'forms'),
('challenge_form.end_date', 'End Date', 'تاريخ النهاية', 'forms'),
('challenge_form.max_participants', 'Maximum Participants', 'الحد الأقصى للمشاركين', 'forms'),
('challenge_form.max_participants_placeholder', 'Enter maximum number of participants', 'أدخل الحد الأقصى لعدد المشاركين', 'forms'),
('challenge_form.tags', 'Tags', 'العلامات', 'forms'),
('challenge_form.tag_selector_coming_soon', 'Tag selector coming soon...', 'محدد العلامات قريباً...', 'forms'),
('challenge_form.challenge_image', 'Challenge Image', 'صورة التحدي', 'forms'),
('challenge_form.saving', 'Saving...', 'جاري الحفظ...', 'forms'),
('challenge_form.save_changes', 'Save Changes', 'حفظ التغييرات', 'forms'),
('challenge_form.cancel', 'Cancel', 'إلغاء', 'forms');