-- Common translations batch
INSERT INTO system_translations (translation_key, text_en, text_ar, category) VALUES
('common.save', 'Save', 'حفظ', 'common'),
('common.cancel', 'Cancel', 'إلغاء', 'common'),
('common.submit', 'Submit', 'إرسال', 'common'),
('common.delete', 'Delete', 'حذف', 'common'),
('common.edit', 'Edit', 'تعديل', 'common'),
('common.view', 'View', 'عرض', 'common'),
('common.manage', 'Manage', 'إدارة', 'common'),
('common.actions', 'Actions', 'الإجراءات', 'common'),
('common.status', 'Status', 'الحالة', 'common'),
('common.loading', 'Loading...', 'جاري التحميل...', 'common'),
('common.error', 'Error', 'خطأ', 'common'),
('common.success', 'Success', 'نجح', 'common'),
('common.refresh', 'Refresh', 'تحديث', 'common'),
('common.yes', 'Yes', 'نعم', 'common'),
('common.no', 'No', 'لا', 'common'),
('common.enabled', 'Enabled', 'مفعل', 'common'),
('common.disabled', 'Disabled', 'معطل', 'common'),
('common.days', 'Days', 'أيام', 'common'),
('common.more', 'More', 'المزيد', 'common'),
('common.completed', 'Completed', 'مكتمل', 'common'),
('common.pending', 'Pending', 'معلق', 'common'),
('common.apply', 'Apply', 'تقديم', 'common'),
('common.review', 'Review', 'مراجعة', 'common'),
('common.no_deadline', 'No Deadline', 'بلا موعد نهائي', 'common'),
('common.frequency.daily', 'Daily', 'يومي', 'common'),
('common.frequency.weekly', 'Weekly', 'أسبوعي', 'common'),
('common.frequency.monthly', 'Monthly', 'شهري', 'common')
ON CONFLICT (translation_key) DO NOTHING;