-- Continue adding missing translation keys (Progress: 391 + ~200 more = ~591 total)

-- Page-specific translations from Index.tsx and other pages
INSERT INTO system_translations (translation_key, text_en, text_ar, category) VALUES
('myIdeas', 'My Ideas', 'أفكاري', 'navigation'),
('ideasManagement', 'Ideas Management', 'إدارة الأفكار', 'navigation'),
('evaluations', 'Evaluations', 'التقييمات', 'navigation'),
('expertiseProfile', 'Expertise Profile', 'الملف الشخصي للخبرة', 'navigation'),
('campaignManagementDesc', 'Campaign Management', 'إدارة الحملات', 'navigation'),
('campaignsContentPlaceholder', 'Campaigns content coming soon', 'محتوى الحملات قريباً', 'navigation'),
('eventManagementDesc', 'Event Management', 'إدارة الفعاليات', 'navigation'),
('eventsContentPlaceholder', 'Events content coming soon', 'محتوى الفعاليات قريباً', 'navigation'),
('innovationTeamsNav', 'Innovation Teams', 'فرق الابتكار', 'navigation'),
('manageCoordinateTeams', 'Manage and coordinate teams', 'إدارة وتنسيق الفرق', 'navigation'),
('stakeholders', 'Stakeholders', 'أصحاب المصلحة', 'navigation'),

-- Campaign Wizard translations
('campaign_wizard.basic_info', 'Basic Information', 'المعلومات الأساسية', 'campaign'),
('campaign_wizard.details_targets', 'Details & Targets', 'التفاصيل والأهداف', 'campaign'),
('campaign_wizard.dates_budget', 'Dates & Budget', 'التواريخ والميزانية', 'campaign'),
('campaign_wizard.organizational_structure', 'Organizational Structure', 'الهيكل التنظيمي', 'campaign'),
('campaign_wizard.links_partnerships', 'Links & Partnerships', 'الروابط والشراكات', 'campaign'),

-- Challenge Settings translations
('challenge_settings.title', 'Challenge Settings', 'إعدادات التحدي', 'challenge'),
('challenge_settings.settings_updated', 'Settings Updated', 'تم تحديث الإعدادات', 'challenge'),
('challenge_settings.settings_updated_description', 'Challenge settings have been updated successfully', 'تم تحديث إعدادات التحدي بنجاح', 'challenge'),
('challenge_settings.error', 'Error', 'خطأ', 'challenge'),
('challenge_settings.error_update_description', 'Failed to update challenge settings', 'فشل في تحديث إعدادات التحدي', 'challenge'),
('challenge_settings.challenge_archived', 'Challenge Archived', 'تم أرشفة التحدي', 'challenge'),
('challenge_settings.challenge_archived_description', 'The challenge has been archived successfully', 'تم أرشفة التحدي بنجاح', 'challenge'),
('challenge_settings.error_archive_description', 'Failed to archive challenge', 'فشل في أرشفة التحدي', 'challenge'),
('challenge_settings.access_control', 'Access Control', 'التحكم في الوصول', 'challenge'),
('challenge_settings.notifications', 'Notifications', 'الإشعارات', 'challenge'),
('challenge_settings.workflow', 'Workflow', 'سير العمل', 'challenge'),
('challenge_settings.advanced', 'Advanced', 'متقدم', 'challenge'),
('challenge_settings.visibility_access', 'Visibility & Access', 'الرؤية والوصول', 'challenge'),

-- System Settings translations
('system_settings_page.title', 'System Settings', 'إعدادات النظام', 'settings'),
('system_settings_page.challenges', 'Challenges', 'التحديات', 'settings'),
('system_settings_page.ideas', 'Ideas', 'الأفكار', 'settings'),
('system_settings_page.events', 'Events', 'الفعاليات', 'settings'),
('system_settings_page.campaigns', 'Campaigns', 'الحملات', 'settings'),
('system_settings_page.partners', 'Partners', 'الشركاء', 'settings'),
('system_settings_page.opportunities', 'Opportunities', 'الفرص', 'settings'),
('system_settings_page.analytics', 'Analytics', 'التحليلات', 'settings'),
('system_settings_page.ai', 'AI Features', 'ميزات الذكاء الاصطناعي', 'settings'),
('system_settings_page.ui', 'User Interface', 'واجهة المستخدم', 'settings'),
('system_settings_page.performance', 'Performance', 'الأداء', 'settings'),
('system_settings_page.translation_management', 'Translation Management', 'إدارة الترجمة', 'settings'),
('system_settings_page.shared_settings', 'Shared Settings', 'الإعدادات المشتركة', 'settings'),

-- System and application translations
('systemSettings', 'System Settings', 'إعدادات النظام', 'system'),
('systemSettingsDescription', 'Manage system-wide settings and configurations', 'إدارة الإعدادات والتكوينات على مستوى النظام', 'system'),
('sharedSettingsDescription', 'Settings that are shared across the entire application', 'الإعدادات المشتركة عبر التطبيق بأكمله', 'system'),

-- Additional common translations
('edit', 'Edit', 'تعديل', 'general'),
('view', 'View', 'عرض', 'general'),
('add', 'Add', 'إضافة', 'general'),
('remove', 'Remove', 'إزالة', 'general'),
('delete_confirm', 'Are you sure you want to delete?', 'هل أنت متأكد من الحذف؟', 'general'),
('back', 'Back', 'رجوع', 'general'),
('next', 'Next', 'التالي', 'general'),
('previous', 'Previous', 'السابق', 'general'),
('finish', 'Finish', 'إنهاء', 'general'),
('continue', 'Continue', 'متابعة', 'general'),
('skip', 'Skip', 'تخطي', 'general'),
('optional', 'Optional', 'اختياري', 'general'),
('required', 'Required', 'مطلوب', 'general'),
('saved', 'Saved', 'محفوظ', 'general'),
('unsaved', 'Unsaved', 'غير محفوظ', 'general'),
('draft_saved', 'Draft saved', 'تم حفظ المسودة', 'general'),
('auto_save', 'Auto-save', 'حفظ تلقائي', 'general'),

-- Status translations
('published', 'Published', 'منشور', 'status'),
('scheduled', 'Scheduled', 'مجدول', 'status'),
('archived', 'Archived', 'مؤرشف', 'status'),
('deleted', 'Deleted', 'محذوف', 'status'),
('suspended', 'Suspended', 'معلق', 'status'),
('expired', 'Expired', 'منتهي الصلاحية', 'status'),
('upcoming', 'Upcoming', 'قادم', 'status'),
('ongoing', 'Ongoing', 'جاري', 'status'),
('completed', 'Completed', 'مكتمل', 'status'),
('cancelled', 'Cancelled', 'ملغي', 'status'),
('postponed', 'Postponed', 'مؤجل', 'status'),

-- Form validation and interaction
('field_required', 'This field is required', 'هذا الحقل مطلوب', 'validation'),
('email_invalid', 'Invalid email format', 'تنسيق البريد الإلكتروني غير صحيح', 'validation'),
('password_weak', 'Password is too weak', 'كلمة المرور ضعيفة جداً', 'validation'),
('confirm_password', 'Confirm Password', 'تأكيد كلمة المرور', 'validation'),
('passwords_mismatch', 'Passwords do not match', 'كلمات المرور غير متطابقة', 'validation'),
('save_draft', 'Save as Draft', 'حفظ كمسودة', 'form'),
('publish', 'Publish', 'نشر', 'form'),
('preview', 'Preview', 'معاينة', 'form'),
('discard', 'Discard', 'تجاهل', 'form'),
('restore', 'Restore', 'استعادة', 'form'),
('duplicate', 'Duplicate', 'نسخ', 'form'),
('archive', 'Archive', 'أرشفة', 'form'),
('unarchive', 'Unarchive', 'إلغاء الأرشفة', 'form'),

-- User interface elements
('sidebar', 'Sidebar', 'الشريط الجانبي', 'ui'),
('header', 'Header', 'الرأس', 'ui'),
('footer', 'Footer', 'التذييل', 'ui'),
('menu', 'Menu', 'القائمة', 'ui'),
('dropdown', 'Dropdown', 'القائمة المنسدلة', 'ui'),
('tooltip', 'Tooltip', 'تلميح', 'ui'),
('modal', 'Modal', 'نافذة منبثقة', 'ui'),
('dialog', 'Dialog', 'حوار', 'ui'),
('popup', 'Popup', 'نافذة منبثقة', 'ui'),
('notification', 'Notification', 'إشعار', 'ui'),
('alert', 'Alert', 'تنبيه', 'ui'),
('warning', 'Warning', 'تحذير', 'ui'),
('info', 'Information', 'معلومات', 'ui'),
('success', 'Success', 'نجح', 'ui'),
('error', 'Error', 'خطأ', 'ui'),
('loading_state', 'Loading...', 'جاري التحميل...', 'ui'),
('empty_state', 'No data to display', 'لا توجد بيانات للعرض', 'ui'),

-- Data and content management
('content', 'Content', 'المحتوى', 'content'),
('metadata', 'Metadata', 'البيانات الوصفية', 'content'),
('tags', 'Tags', 'العلامات', 'content'),
('categories', 'Categories', 'الفئات', 'content'),
('labels', 'Labels', 'التسميات', 'content'),
('keywords', 'Keywords', 'الكلمات المفتاحية', 'content'),
('attachments', 'Attachments', 'المرفقات', 'content'),
('files', 'Files', 'الملفات', 'content'),
('images', 'Images', 'الصور', 'content'),
('videos', 'Videos', 'مقاطع الفيديو', 'content'),
('documents', 'Documents', 'الوثائق', 'content'),
('links', 'Links', 'الروابط', 'content'),
('references', 'References', 'المراجع', 'content'),

-- Time and scheduling
('time', 'Time', 'الوقت', 'time'),
('date', 'Date', 'التاريخ', 'time'),
('datetime', 'Date & Time', 'التاريخ والوقت', 'time'),
('deadline', 'Deadline', 'الموعد النهائي', 'time'),
('due_date', 'Due Date', 'تاريخ الاستحقاق', 'time'),
('created_at', 'Created At', 'تاريخ الإنشاء', 'time'),
('updated_at', 'Updated At', 'تاريخ التحديث', 'time'),
('published_at', 'Published At', 'تاريخ النشر', 'time'),
('scheduled_at', 'Scheduled At', 'مجدول في', 'time'),
('expires_at', 'Expires At', 'ينتهي في', 'time'),
('duration', 'Duration', 'المدة', 'time'),
('timezone', 'Timezone', 'المنطقة الزمنية', 'time'),

-- Permissions and access
('permissions', 'Permissions', 'الأذونات', 'access'),
('access_level', 'Access Level', 'مستوى الوصول', 'access'),
('public_access', 'Public Access', 'وصول عام', 'access'),
('private_access', 'Private Access', 'وصول خاص', 'access'),
('restricted_access', 'Restricted Access', 'وصول مقيد', 'access'),
('read_only', 'Read Only', 'قراءة فقط', 'access'),
('read_write', 'Read & Write', 'قراءة وكتابة', 'access'),
('admin_only', 'Admin Only', 'المديرين فقط', 'access'),
('owner', 'Owner', 'المالك', 'access'),
('collaborator', 'Collaborator', 'المتعاون', 'access'),
('viewer', 'Viewer', 'المشاهد', 'access'),
('editor', 'Editor', 'المحرر', 'access'),
('moderator', 'Moderator', 'المشرف', 'access'),

-- Communication and collaboration  
('message', 'Message', 'رسالة', 'communication'),
('comment', 'Comment', 'تعليق', 'communication'),
('reply', 'Reply', 'رد', 'communication'),
('mention', 'Mention', 'إشارة', 'communication'),
('notification', 'Notification', 'إشعار', 'communication'),
('email', 'Email', 'البريد الإلكتروني', 'communication'),
('phone', 'Phone', 'الهاتف', 'communication'),
('address', 'Address', 'العنوان', 'communication'),
('contact', 'Contact', 'اتصال', 'communication'),
('feedback', 'Feedback', 'التعليقات', 'communication'),
('review', 'Review', 'مراجعة', 'communication'),
('rating', 'Rating', 'التقييم', 'communication'),
('like', 'Like', 'إعجاب', 'communication'),
('share', 'Share', 'مشاركة', 'communication'),
('follow', 'Follow', 'متابعة', 'communication'),
('unfollow', 'Unfollow', 'إلغاء المتابعة', 'communication'),

-- Statistics and metrics
('statistics', 'Statistics', 'الإحصائيات', 'metrics'),
('metrics', 'Metrics', 'المقاييس', 'metrics'),
('count', 'Count', 'العدد', 'metrics'),
('percentage', 'Percentage', 'النسبة المئوية', 'metrics'),
('average', 'Average', 'المتوسط', 'metrics'),
('minimum', 'Minimum', 'الحد الأدنى', 'metrics'),
('maximum', 'Maximum', 'الحد الأقصى', 'metrics'),
('trend', 'Trend', 'الاتجاه', 'metrics'),
('growth', 'Growth', 'النمو', 'metrics'),
('decline', 'Decline', 'التراجع', 'metrics'),
('change', 'Change', 'التغيير', 'metrics'),
('comparison', 'Comparison', 'مقارنة', 'metrics'),
('report', 'Report', 'تقرير', 'metrics'),
('chart', 'Chart', 'مخطط بياني', 'metrics'),
('graph', 'Graph', 'رسم بياني', 'metrics')

ON CONFLICT (translation_key) DO NOTHING;