-- Add translation keys for AdminNotificationSettings and RoleManagement components

INSERT INTO system_translations (translation_key, text_en, text_ar, category) VALUES
-- AdminNotificationSettings translations
('admin.notification.settings.title', 'Admin Notification Settings', 'إعدادات الإشعارات الإدارية', 'admin'),
('admin.notification.tabs.global', 'Global', 'عام', 'admin'),
('admin.notification.tabs.channels', 'Channels', 'القنوات', 'admin'),
('admin.notification.tabs.templates', 'Templates', 'القوالب', 'admin'),
('admin.notification.tabs.analytics', 'Analytics', 'التحليلات', 'admin'),
('admin.notification.global.title', 'Global Settings', 'الإعدادات العامة', 'admin'),
('admin.notification.global.description', 'Configure system-wide notification settings', 'تكوين إعدادات الإشعارات على مستوى النظام', 'admin'),
('admin.notification.digest.enabled', 'Enable Digest Emails', 'تفعيل رسائل الملخص', 'admin'),
('admin.notification.digest.frequency', 'Digest Frequency', 'تكرار الملخص', 'admin'),
('admin.notification.retention.days', 'Retention Days', 'أيام الاحتفاظ', 'admin'),
('admin.notification.fetch.limit', 'Fetch Limit', 'حد الجلب', 'admin'),
('admin.notification.quiet.hours.enabled', 'Enable Quiet Hours', 'تفعيل الساعات الهادئة', 'admin'),
('admin.notification.quiet.hours.start', 'Quiet Hours Start', 'بداية الساعات الهادئة', 'admin'),
('admin.notification.quiet.hours.end', 'Quiet Hours End', 'نهاية الساعات الهادئة', 'admin'),
('admin.notification.admin.email', 'Admin Email', 'البريد الإلكتروني للمدير', 'admin'),
('admin.notification.user.controls', 'User Controls', 'تحكم المستخدمين', 'admin'),
('admin.notification.user.opt.out', 'Allow User Opt Out', 'السماح للمستخدم بإلغاء الاشتراك', 'admin'),
('admin.notification.email.verification', 'Require Email Verification', 'يتطلب التحقق من البريد الإلكتروني', 'admin'),
('admin.notification.emergency.override', 'Emergency Override', 'تجاوز الطوارئ', 'admin'),
('admin.notification.channel.email', 'Email', 'البريد الإلكتروني', 'admin'),
('admin.notification.channel.sms', 'SMS', 'رسائل نصية', 'admin'),
('admin.notification.channel.push', 'Push', 'الدفع', 'admin'),
('admin.notification.channel.system', 'System', 'النظام', 'admin'),
('admin.notification.test', 'Test', 'اختبار', 'admin'),

-- RoleManagement translations
('roles.super_admin.label', 'Super Admin', 'مدير النظام الرئيسي', 'roles'),
('roles.super_admin.description', 'Full system privileges', 'صلاحيات كاملة على النظام', 'roles'),
('roles.admin.label', 'Admin', 'مدير النظام', 'roles'),
('roles.admin.description', 'User and settings management', 'إدارة المستخدمين والإعدادات', 'roles'),
('roles.org_admin.label', 'Organization Admin', 'مدير الجهة', 'roles'),
('roles.org_admin.description', 'Organization user management', 'إدارة مستخدمي الجهة', 'roles'),
('roles.expert.label', 'Expert', 'خبير تقييم', 'roles'),
('roles.expert.description', 'Evaluate ideas and projects', 'تقييم الأفكار والمشاريع', 'roles'),
('roles.innovator.label', 'Innovator', 'مبتكر', 'roles'),
('roles.innovator.description', 'Submit ideas and participate', 'تقديم الأفكار والمشاركة', 'roles'),
('roles.viewer.label', 'Viewer', 'مطلع', 'roles'),
('roles.viewer.description', 'View content only', 'عرض المحتوى فقط', 'roles'),
('roles.level', 'Level', 'مستوى', 'roles'),
('roles.permissions.count', 'Permissions', 'الصلاحيات', 'roles'),
('roles.permissions.unit', 'permissions', 'صلاحية', 'roles'),
('roles.hierarchy.title', 'Role Hierarchy & Permissions', 'هيكل الأدوار والصلاحيات', 'roles'),
('roles.hierarchy.description', 'Hierarchical role management system for security and proper control', 'نظام إدارة الأدوار المتدرج لضمان الأمان والتحكم المناسب', 'roles'),
('roles.user.management.title', 'User Management', 'إدارة المستخدمين', 'roles'),
('roles.user.management.description', 'Assign and manage user roles in the system', 'تعيين وإدارة أدوار المستخدمين في النظام', 'roles'),
('roles.search.placeholder', 'Search by name or email...', 'بحث بالاسم أو البريد الإلكتروني...', 'roles'),
('roles.filter.placeholder', 'Filter by role', 'تصفية حسب الدور', 'roles'),
('roles.filter.all', 'All Roles', 'جميع الأدوار', 'roles'),
('roles.table.user', 'User', 'المستخدم', 'roles'),
('roles.table.current.role', 'Current Role', 'الدور الحالي', 'roles'),
('roles.table.organization', 'Organization', 'الجهة', 'roles'),
('roles.table.last.activity', 'Last Activity', 'آخر نشاط', 'roles'),
('roles.table.actions', 'Actions', 'الإجراءات', 'roles'),
('roles.update.dialog.title', 'Update User Role', 'تحديث دور المستخدم', 'roles'),
('roles.update.dialog.description', 'Select new role for user', 'اختر الدور الجديد للمستخدم', 'roles'),
('roles.new.role', 'New Role', 'الدور الجديد', 'roles'),
('roles.update.button', 'Update Role', 'تحديث الدور', 'roles'),
('roles.update.success.title', 'Role Updated', 'تم تحديث الدور', 'roles'),
('roles.update.success.description', 'User role has been successfully updated', 'تم تغيير دور المستخدم بنجاح', 'roles'),
('roles.update.error.title', 'Update Error', 'خطأ في التحديث', 'roles'),
('roles.update.error.description', 'An error occurred while updating user role', 'حدث خطأ أثناء تحديث دور المستخدم', 'roles'),
('roles.no.results', 'No matching results found', 'لا توجد نتائج مطابقة للبحث', 'roles'),
('roles.permissions.matrix.title', 'Permissions Matrix', 'مصفوفة الصلاحيات', 'roles'),
('roles.permissions.matrix.description', 'Detailed view of permissions assigned to each role', 'عرض تفصيلي للصلاحيات المخصصة لكل دور', 'roles'),
('roles.permissions.permission', 'Permission', 'الصلاحية', 'roles');