-- Add workspace translations to existing system_translations table

-- Insert workspace translations for User Workspace
INSERT INTO system_translations (translation_key, language_code, translation_text, category) VALUES
('workspace.user.title', 'ar', 'مساحة العمل الشخصية', 'workspace'),
('workspace.user.title', 'en', 'Personal Workspace', 'workspace'),
('workspace.user.description', 'ar', 'مساحة عملك الشخصية لإدارة أنشطتك ومشاريعك', 'workspace'),
('workspace.user.description', 'en', 'Your personal workspace to manage your activities and projects', 'workspace'),
('workspace.user.features.myIdeas', 'ar', 'أفكاري', 'workspace'),
('workspace.user.features.myIdeas', 'en', 'My Ideas', 'workspace'),
('workspace.user.features.mySubmissions', 'ar', 'مساهماتي', 'workspace'),
('workspace.user.features.mySubmissions', 'en', 'My Submissions', 'workspace'),
('workspace.user.features.favoriteEvents', 'ar', 'الفعاليات المفضلة', 'workspace'),
('workspace.user.features.favoriteEvents', 'en', 'Favorite Events', 'workspace'),
('workspace.user.features.bookmarkedChallenges', 'ar', 'التحديات المحفوظة', 'workspace'),
('workspace.user.features.bookmarkedChallenges', 'en', 'Bookmarked Challenges', 'workspace'),
('workspace.user.features.notificationSettings', 'ar', 'إعدادات الإشعارات', 'workspace'),
('workspace.user.features.notificationSettings', 'en', 'Notification Settings', 'workspace'),
('workspace.user.features.profileManagement', 'ar', 'إدارة الملف الشخصي', 'workspace'),
('workspace.user.features.profileManagement', 'en', 'Profile Management', 'workspace'),

-- Insert workspace translations for Expert Workspace
('workspace.expert.title', 'ar', 'مساحة عمل الخبير', 'workspace'),
('workspace.expert.title', 'en', 'Expert Workspace', 'workspace'),
('workspace.expert.description', 'ar', 'مساحة عمل متخصصة للخبراء لتقييم الأفكار وإدارة التحديات', 'workspace'),
('workspace.expert.description', 'en', 'Specialized workspace for experts to evaluate ideas and manage challenges', 'workspace'),
('workspace.expert.features.ideaEvaluation', 'ar', 'تقييم الأفكار', 'workspace'),
('workspace.expert.features.ideaEvaluation', 'en', 'Idea Evaluation', 'workspace'),
('workspace.expert.features.challengeReview', 'ar', 'مراجعة التحديات', 'workspace'),
('workspace.expert.features.challengeReview', 'en', 'Challenge Review', 'workspace'),
('workspace.expert.features.scorecardManagement', 'ar', 'إدارة بطاقات التقييم', 'workspace'),
('workspace.expert.features.scorecardManagement', 'en', 'Scorecard Management', 'workspace'),
('workspace.expert.features.expertFeedback', 'ar', 'ملاحظات الخبراء', 'workspace'),
('workspace.expert.features.expertFeedback', 'en', 'Expert Feedback', 'workspace'),
('workspace.expert.features.reportGeneration', 'ar', 'إنشاء التقارير', 'workspace'),
('workspace.expert.features.reportGeneration', 'en', 'Report Generation', 'workspace'),
('workspace.expert.features.mentorshipActivities', 'ar', 'أنشطة التوجيه', 'workspace'),
('workspace.expert.features.mentorshipActivities', 'en', 'Mentorship Activities', 'workspace'),

-- Insert workspace translations for Organization Workspace
('workspace.organization.title', 'ar', 'مساحة عمل المؤسسة', 'workspace'),
('workspace.organization.title', 'en', 'Organization Workspace', 'workspace'),
('workspace.organization.description', 'ar', 'مساحة عمل المؤسسة لإدارة التحديات والفعاليات والمشاريع', 'workspace'),
('workspace.organization.description', 'en', 'Organization workspace for managing challenges, events, and projects', 'workspace'),
('workspace.organization.features.challengeManagement', 'ar', 'إدارة التحديات', 'workspace'),
('workspace.organization.features.challengeManagement', 'en', 'Challenge Management', 'workspace'),
('workspace.organization.features.eventCoordination', 'ar', 'تنسيق الفعاليات', 'workspace'),
('workspace.organization.features.eventCoordination', 'en', 'Event Coordination', 'workspace'),
('workspace.organization.features.teamCollaboration', 'ar', 'تعاون الفريق', 'workspace'),
('workspace.organization.features.teamCollaboration', 'en', 'Team Collaboration', 'workspace'),
('workspace.organization.features.resourcePlanning', 'ar', 'تخطيط الموارد', 'workspace'),
('workspace.organization.features.resourcePlanning', 'en', 'Resource Planning', 'workspace'),
('workspace.organization.features.stakeholderCommunication', 'ar', 'التواصل مع أصحاب المصلحة', 'workspace'),
('workspace.organization.features.stakeholderCommunication', 'en', 'Stakeholder Communication', 'workspace'),
('workspace.organization.features.progressTracking', 'ar', 'تتبع التقدم', 'workspace'),
('workspace.organization.features.progressTracking', 'en', 'Progress Tracking', 'workspace'),

-- Insert workspace translations for Partner Workspace
('workspace.partner.title', 'ar', 'مساحة عمل الشريك', 'workspace'),
('workspace.partner.title', 'en', 'Partner Workspace', 'workspace'),
('workspace.partner.description', 'ar', 'مساحة عمل للشركاء للتعاون والمساهمة في المشاريع والحلول', 'workspace'),
('workspace.partner.description', 'en', 'Partner workspace for collaboration and contribution to projects and solutions', 'workspace'),
('workspace.partner.features.partnershipManagement', 'ar', 'إدارة الشراكات', 'workspace'),
('workspace.partner.features.partnershipManagement', 'en', 'Partnership Management', 'workspace'),
('workspace.partner.features.resourceContribution', 'ar', 'مساهمة الموارد', 'workspace'),
('workspace.partner.features.resourceContribution', 'en', 'Resource Contribution', 'workspace'),
('workspace.partner.features.collaborativeProjects', 'ar', 'المشاريع التعاونية', 'workspace'),
('workspace.partner.features.collaborativeProjects', 'en', 'Collaborative Projects', 'workspace'),
('workspace.partner.features.marketplaceAccess', 'ar', 'الوصول للسوق', 'workspace'),
('workspace.partner.features.marketplaceAccess', 'en', 'Marketplace Access', 'workspace'),
('workspace.partner.features.networkingOpportunities', 'ar', 'فرص التواصل', 'workspace'),
('workspace.partner.features.networkingOpportunities', 'en', 'Networking Opportunities', 'workspace'),
('workspace.partner.features.performanceMetrics', 'ar', 'مقاييس الأداء', 'workspace'),
('workspace.partner.features.performanceMetrics', 'en', 'Performance Metrics', 'workspace'),

-- Insert workspace translations for Admin Workspace
('workspace.admin.title', 'ar', 'مساحة عمل الإدارة', 'workspace'),
('workspace.admin.title', 'en', 'Admin Workspace', 'workspace'),
('workspace.admin.description', 'ar', 'مساحة عمل شاملة لإدارة النظام والمستخدمين والعمليات', 'workspace'),
('workspace.admin.description', 'en', 'Comprehensive workspace for system, user, and operations management', 'workspace'),
('workspace.admin.features.systemConfiguration', 'ar', 'إعدادات النظام', 'workspace'),
('workspace.admin.features.systemConfiguration', 'en', 'System Configuration', 'workspace'),
('workspace.admin.features.userManagement', 'ar', 'إدارة المستخدمين', 'workspace'),
('workspace.admin.features.userManagement', 'en', 'User Management', 'workspace'),
('workspace.admin.features.rolePermissions', 'ar', 'أذونات الأدوار', 'workspace'),
('workspace.admin.features.rolePermissions', 'en', 'Role Permissions', 'workspace'),
('workspace.admin.features.dataAnalytics', 'ar', 'تحليل البيانات', 'workspace'),
('workspace.admin.features.dataAnalytics', 'en', 'Data Analytics', 'workspace'),
('workspace.admin.features.securityMonitoring', 'ar', 'مراقبة الأمان', 'workspace'),
('workspace.admin.features.securityMonitoring', 'en', 'Security Monitoring', 'workspace'),
('workspace.admin.features.systemMaintenance', 'ar', 'صيانة النظام', 'workspace'),
('workspace.admin.features.systemMaintenance', 'en', 'System Maintenance', 'workspace'),

-- Insert workspace translations for Team Workspace
('workspace.team.title', 'ar', 'مساحة عمل الفريق', 'workspace'),
('workspace.team.title', 'en', 'Team Workspace', 'workspace'),
('workspace.team.description', 'ar', 'مساحة عمل تعاونية لفرق الابتكار لإدارة المشاريع والمهام', 'workspace'),
('workspace.team.description', 'en', 'Collaborative workspace for innovation teams to manage projects and tasks', 'workspace'),
('workspace.team.features.projectManagement', 'ar', 'إدارة المشاريع', 'workspace'),
('workspace.team.features.projectManagement', 'en', 'Project Management', 'workspace'),
('workspace.team.features.taskAssignment', 'ar', 'تكليف المهام', 'workspace'),
('workspace.team.features.taskAssignment', 'en', 'Task Assignment', 'workspace'),
('workspace.team.features.capacityPlanning', 'ar', 'تخطيط القدرات', 'workspace'),
('workspace.team.features.capacityPlanning', 'en', 'Capacity Planning', 'workspace'),
('workspace.team.features.workloadTracking', 'ar', 'تتبع عبء العمل', 'workspace'),
('workspace.team.features.workloadTracking', 'en', 'Workload Tracking', 'workspace'),
('workspace.team.features.performanceMetrics', 'ar', 'مقاييس الأداء', 'workspace'),
('workspace.team.features.performanceMetrics', 'en', 'Performance Metrics', 'workspace'),
('workspace.team.features.communicationTools', 'ar', 'أدوات التواصل', 'workspace'),
('workspace.team.features.communicationTools', 'en', 'Communication Tools', 'workspace'),

-- Insert general workspace translations
('workspace.concept.definition', 'ar', 'مساحة العمل هي بيئة عمل تفاعلية مخصصة لدور المستخدم، تركز على المهام والإنتاجية والتعاون', 'workspace'),
('workspace.concept.definition', 'en', 'A workspace is an interactive work environment tailored to the user role, focused on tasks, productivity, and collaboration', 'workspace'),
('workspace.vs.dashboard.workspace', 'ar', 'مساحة العمل: بيئة نشطة للعمل والتعاون وإنجاز المهام', 'workspace'),
('workspace.vs.dashboard.workspace', 'en', 'Workspace: Active environment for work, collaboration, and task completion', 'workspace'),
('workspace.vs.dashboard.dashboard', 'ar', 'لوحة المعلومات: عرض سلبي للمعلومات والإحصائيات', 'workspace'),
('workspace.vs.dashboard.dashboard', 'en', 'Dashboard: Passive display of information and analytics', 'workspace'),
('workspace.navigation.workspaces', 'ar', 'مساحات العمل', 'workspace'),
('workspace.navigation.workspaces', 'en', 'Workspaces', 'workspace'),
('workspace.common.features', 'ar', 'المميزات', 'workspace'),
('workspace.common.features', 'en', 'Features', 'workspace'),
('workspace.common.tools', 'ar', 'الأدوات', 'workspace'),
('workspace.common.tools', 'en', 'Tools', 'workspace'),
('workspace.common.activities', 'ar', 'الأنشطة', 'workspace'),
('workspace.common.activities', 'en', 'Activities', 'workspace'),
('workspace.common.collaboration', 'ar', 'التعاون', 'workspace'),
('workspace.common.collaboration', 'en', 'Collaboration', 'workspace');