-- Add missing basic UI translations that are showing up in logs
INSERT INTO system_translations (translation_key, language_code, translation_text, category) VALUES
-- Basic navigation translations
('all', 'en', 'All', 'navigation'),
('all', 'ar', 'الكل', 'navigation'),
('open_navigation', 'en', 'Open navigation', 'accessibility'),
('open_navigation', 'ar', 'فتح التنقل', 'accessibility'),
('toggle_direction', 'en', 'Toggle direction', 'accessibility'),
('toggle_direction', 'ar', 'تبديل الاتجاه', 'accessibility'),
('toggle_theme', 'en', 'Toggle theme', 'accessibility'),
('toggle_theme', 'ar', 'تبديل المظهر', 'accessibility'),

-- Time-related translations
('just_now', 'en', 'Just now', 'time'),
('just_now', 'ar', 'الآن', 'time'),
('minutes_ago', 'en', '{{count}} minute ago', 'time'),
('minutes_ago', 'ar', 'منذ {{count}} دقيقة', 'time'),
('minutes_ago_plural', 'en', '{{count}} minutes ago', 'time'),
('minutes_ago_plural', 'ar', 'منذ {{count}} دقائق', 'time'),
('hours_ago', 'en', '{{count}} hour ago', 'time'),
('hours_ago', 'ar', 'منذ {{count}} ساعة', 'time'),
('hours_ago_plural', 'en', '{{count}} hours ago', 'time'),
('hours_ago_plural', 'ar', 'منذ {{count}} ساعات', 'time'),
('days_ago', 'en', '{{count}} day ago', 'time'),
('days_ago', 'ar', 'منذ {{count}} يوم', 'time'),
('days_ago_plural', 'en', '{{count}} days ago', 'time'),
('days_ago_plural', 'ar', 'منذ {{count}} أيام', 'time'),

-- Common UI elements
('loading', 'en', 'Loading...', 'ui'),
('loading', 'ar', 'جاري التحميل...', 'ui'),
('save', 'en', 'Save', 'ui'),
('save', 'ar', 'حفظ', 'ui'),
('cancel', 'en', 'Cancel', 'ui'),
('cancel', 'ar', 'إلغاء', 'ui'),
('edit', 'en', 'Edit', 'ui'),
('edit', 'ar', 'تعديل', 'ui'),
('delete', 'en', 'Delete', 'ui'),
('delete', 'ar', 'حذف', 'ui'),
('add', 'en', 'Add', 'ui'),
('add', 'ar', 'إضافة', 'ui'),
('search', 'en', 'Search', 'ui'),
('search', 'ar', 'بحث', 'ui'),
('close', 'en', 'Close', 'ui'),
('close', 'ar', 'إغلاق', 'ui'),
('open', 'en', 'Open', 'ui'),
('open', 'ar', 'فتح', 'ui'),
('submit', 'en', 'Submit', 'ui'),
('submit', 'ar', 'إرسال', 'ui'),
('confirm', 'en', 'Confirm', 'ui'),
('confirm', 'ar', 'تأكيد', 'ui'),
('back', 'en', 'Back', 'ui'),
('back', 'ar', 'رجوع', 'ui'),
('next', 'en', 'Next', 'ui'),
('next', 'ar', 'التالي', 'ui'),
('previous', 'en', 'Previous', 'ui'),
('previous', 'ar', 'السابق', 'ui'),
('home', 'en', 'Home', 'ui'),
('home', 'ar', 'الرئيسية', 'ui'),
('dashboard', 'en', 'Dashboard', 'ui'),
('dashboard', 'ar', 'لوحة التحكم', 'ui')

ON CONFLICT (translation_key, language_code) DO UPDATE SET
translation_text = EXCLUDED.translation_text,
updated_at = now();