-- Add comprehensive missing translation keys for system settings
INSERT INTO public.system_translations (translation_key, text_en, text_ar, category) VALUES

-- Category translations
('settings.category.access', 'Access Management', 'إدارة الوصول', 'settings'),
('settings.category.access.description', 'Configure access control and visibility settings', 'تكوين إعدادات التحكم في الوصول والرؤية', 'settings'),
('settings.category.access_control', 'Access Control', 'التحكم في الوصول', 'settings'),
('settings.category.access_control.description', 'Advanced access control configurations', 'إعدادات التحكم في الوصول المتقدمة', 'settings'),
('settings.category.api_settings', 'API Settings', 'إعدادات واجهة برمجة التطبيقات', 'settings'),
('settings.category.api_settings.description', 'Configure API rate limits and access', 'تكوين حدود واجهة برمجة التطبيقات والوصول', 'settings'),
('settings.category.array_lists', 'Array Lists', 'القوائم المصفوفة', 'settings'),
('settings.category.array_lists.description', 'Manage system array configurations', 'إدارة إعدادات المصفوفات النظام', 'settings'),
('settings.category.assignment', 'Assignments', 'المهام', 'settings'),
('settings.category.assignment.description', 'Configure assignment and task settings', 'تكوين إعدادات المهام والواجبات', 'settings'),
('settings.category.auth', 'Authentication', 'المصادقة', 'settings'),
('settings.category.auth.description', 'Authentication and authorization settings', 'إعدادات المصادقة والتخويل', 'settings'),
('settings.category.authentication', 'Authentication', 'المصادقة', 'settings'),
('settings.category.authentication.description', 'User authentication configurations', 'إعدادات مصادقة المستخدمين', 'settings'),
('settings.category.challenge', 'Challenge Settings', 'إعدادات التحديات', 'settings'),
('settings.category.challenge.description', 'Challenge-specific configurations', 'إعدادات خاصة بالتحديات', 'settings'),
('settings.category.Challenge Management', 'Challenge Management', 'إدارة التحديات', 'settings'),
('settings.category.Challenge Management.description', 'Advanced challenge management settings', 'إعدادات إدارة التحديات المتقدمة', 'settings'),
('settings.category.challenge_management', 'Challenge Management', 'إدارة التحديات', 'settings'),
('settings.category.challenge_management.description', 'Comprehensive challenge management settings', 'إعدادات إدارة التحديات الشاملة', 'settings'),
('settings.category.data', 'Data Management', 'إدارة البيانات', 'settings'),
('settings.category.data.description', 'Data export and management settings', 'إعدادات تصدير وإدارة البيانات', 'settings'),
('settings.category.evaluations', 'Evaluations', 'التقييمات', 'settings'),
('settings.category.evaluations.description', 'Evaluation criteria and settings', 'معايير وإعدادات التقييم', 'settings'),
('settings.category.event', 'Event Settings', 'إعدادات الفعاليات', 'settings'),
('settings.category.event.description', 'Event-specific configurations', 'إعدادات خاصة بالفعاليات', 'settings'),
('settings.category.expert', 'Expert Management', 'إدارة الخبراء', 'settings'),
('settings.category.expert.description', 'Expert-specific settings and configurations', 'إعدادات وتكوينات خاصة بالخبراء', 'settings'),
('settings.category.Expert Management', 'Expert Management', 'إدارة الخبراء', 'settings'),
('settings.category.Expert Management.description', 'Advanced expert management configurations', 'إعدادات إدارة الخبراء المتقدمة', 'settings'),
('settings.category.expert_management', 'Expert Management', 'إدارة الخبراء', 'settings'),
('settings.category.expert_management.description', 'Comprehensive expert management settings', 'إعدادات إدارة الخبراء الشاملة', 'settings'),
('settings.category.file_upload', 'File Upload', 'رفع الملفات', 'settings'),
('settings.category.file_upload.description', 'File upload and MIME type settings', 'إعدادات رفع الملفات وأنواع MIME', 'settings'),
('settings.category.files', 'File Management', 'إدارة الملفات', 'settings'),
('settings.category.files.description', 'File categories and management settings', 'فئات الملفات وإعدادات الإدارة', 'settings'),
('settings.category.focus_question', 'Focus Questions', 'أسئلة التركيز', 'settings'),
('settings.category.focus_question.description', 'Focus question configurations', 'إعدادات أسئلة التركيز', 'settings'),
('settings.category.focus_questions', 'Focus Questions', 'أسئلة التركيز', 'settings'),
('settings.category.focus_questions.description', 'Advanced focus question settings', 'إعدادات أسئلة التركيز المتقدمة', 'settings'),
('settings.category.form_validation', 'Form Validation', 'تحقق النماذج', 'settings'),
('settings.category.form_validation.description', 'Form validation rules and limits', 'قواعد وحدود تحقق النماذج', 'settings'),
('settings.category.global_lists', 'Global Lists', 'القوائم العامة', 'settings'),
('settings.category.global_lists.description', 'System-wide list configurations', 'إعدادات القوائم على مستوى النظام', 'settings'),
('settings.category.i18n', 'Internationalization', 'التدويل', 'settings'),
('settings.category.i18n.description', 'Language and localization settings', 'إعدادات اللغة والتوطين', 'settings'),
('settings.category.integration', 'Integration', 'التكامل', 'settings'),
('settings.category.integration.description', 'System integration settings', 'إعدادات تكامل النظام', 'settings'),
('settings.category.integrations', 'Integrations', 'التكاملات', 'settings'),
('settings.category.integrations.description', 'External service integrations', 'تكاملات الخدمات الخارجية', 'settings'),
('settings.category.Lists', 'Lists', 'القوائم', 'settings'),
('settings.category.Lists.description', 'System list configurations', 'إعدادات قوائم النظام', 'settings'),
('settings.category.navigation', 'Navigation', 'التنقل', 'settings'),
('settings.category.navigation.description', 'Navigation and menu settings', 'إعدادات التنقل والقوائم', 'settings'),
('settings.category.notification', 'Notifications', 'الإشعارات', 'settings'),
('settings.category.notification.description', 'Notification configurations', 'إعدادات الإشعارات', 'settings'),
('settings.category.notifications', 'Notifications', 'الإشعارات', 'settings'),
('settings.category.notifications.description', 'Advanced notification settings', 'إعدادات الإشعارات المتقدمة', 'settings'),
('settings.category.organizational', 'Organizational', 'التنظيمي', 'settings'),
('settings.category.organizational.description', 'Organizational structure settings', 'إعدادات الهيكل التنظيمي', 'settings'),
('settings.category.partner', 'Partner Management', 'إدارة الشركاء', 'settings'),
('settings.category.partner.description', 'Partner-specific settings', 'إعدادات خاصة بالشركاء', 'settings'),
('settings.category.profiles', 'User Profiles', 'ملفات المستخدمين', 'settings'),
('settings.category.profiles.description', 'User profile configurations', 'إعدادات ملفات المستخدمين', 'settings'),
('settings.category.questions', 'Questions', 'الأسئلة', 'settings'),
('settings.category.questions.description', 'Question management settings', 'إعدادات إدارة الأسئلة', 'settings'),
('settings.category.role', 'Role Management', 'إدارة الأدوار', 'settings'),
('settings.category.role.description', 'Role request and management settings', 'إعدادات طلب وإدارة الأدوار', 'settings'),
('settings.category.role_management', 'Role Management', 'إدارة الأدوار', 'settings'),
('settings.category.role_management.description', 'Advanced role management configurations', 'إعدادات إدارة الأدوار المتقدمة', 'settings'),
('settings.category.roles', 'Roles', 'الأدوار', 'settings'),
('settings.category.roles.description', 'System role configurations', 'إعدادات أدوار النظام', 'settings'),
('settings.category.stakeholder', 'Stakeholder Management', 'إدارة أصحاب المصلحة', 'settings'),
('settings.category.stakeholder.description', 'Stakeholder-specific settings', 'إعدادات خاصة بأصحاب المصلحة', 'settings'),
('settings.category.stakeholders', 'Stakeholders', 'أصحاب المصلحة', 'settings'),
('settings.category.stakeholders.description', 'Advanced stakeholder settings', 'إعدادات أصحاب المصلحة المتقدمة', 'settings'),
('settings.category.storage', 'Storage', 'التخزين', 'settings'),
('settings.category.storage.description', 'File storage and management', 'تخزين وإدارة الملفات', 'settings'),
('settings.category.system', 'System Configuration', 'تكوين النظام', 'settings'),
('settings.category.system.description', 'Core system settings', 'إعدادات النظام الأساسية', 'settings'),
('settings.category.team', 'Team Management', 'إدارة الفرق', 'settings'),
('settings.category.team.description', 'Team-specific configurations', 'إعدادات خاصة بالفرق', 'settings'),
('settings.category.Team Management', 'Team Management', 'إدارة الفرق', 'settings'),
('settings.category.Team Management.description', 'Advanced team management settings', 'إعدادات إدارة الفرق المتقدمة', 'settings'),
('settings.category.team_management', 'Team Management', 'إدارة الفرق', 'settings'),
('settings.category.team_management.description', 'Comprehensive team management', 'إدارة الفرق الشاملة', 'settings'),
('settings.category.teams', 'Teams', 'الفرق', 'settings'),
('settings.category.teams.description', 'Team configurations and settings', 'إعدادات وتكوينات الفرق', 'settings'),
('settings.category.testing', 'Testing', 'الاختبار', 'settings'),
('settings.category.testing.description', 'Testing and development settings', 'إعدادات الاختبار والتطوير', 'settings'),
('settings.category.UI & Form', 'UI & Forms', 'واجهة المستخدم والنماذج', 'settings'),
('settings.category.UI & Form.description', 'User interface and form settings', 'إعدادات واجهة المستخدم والنماذج', 'settings'),
('settings.category.ui_animations', 'UI Animations', 'رسوم متحركة لواجهة المستخدم', 'settings'),
('settings.category.ui_animations.description', 'Animation and transition settings', 'إعدادات الرسوم المتحركة والانتقالات', 'settings'),
('settings.category.ui_defaults', 'UI Defaults', 'افتراضيات واجهة المستخدم', 'settings'),
('settings.category.ui_defaults.description', 'Default UI element settings', 'إعدادات عناصر واجهة المستخدم الافتراضية', 'settings'),
('settings.category.ui_feedback', 'UI Feedback', 'تعليقات واجهة المستخدم', 'settings'),
('settings.category.ui_feedback.description', 'User feedback and rating settings', 'إعدادات تعليقات وتقييمات المستخدمين', 'settings'),
('settings.category.ui_layout', 'UI Layout', 'تخطيط واجهة المستخدم', 'settings'),
('settings.category.ui_layout.description', 'User interface layout options', 'خيارات تخطيط واجهة المستخدم', 'settings'),
('settings.category.ui_navigation', 'UI Navigation', 'تنقل واجهة المستخدم', 'settings'),
('settings.category.ui_navigation.description', 'Navigation interface settings', 'إعدادات واجهة التنقل', 'settings'),
('settings.category.ui_settings', 'UI Settings', 'إعدادات واجهة المستخدم', 'settings'),
('settings.category.ui_settings.description', 'General user interface settings', 'إعدادات واجهة المستخدم العامة', 'settings'),
('settings.category.ui_theme', 'UI Theme', 'مظهر واجهة المستخدم', 'settings'),
('settings.category.ui_theme.description', 'Theme and color settings', 'إعدادات المظهر والألوان', 'settings'),
('settings.category.user', 'User Management', 'إدارة المستخدمين', 'settings'),
('settings.category.user.description', 'User account and role settings', 'إعدادات حسابات المستخدمين والأدوار', 'settings'),
('settings.category.User Profile', 'User Profiles', 'ملفات المستخدمين', 'settings'),
('settings.category.User Profile.description', 'User profile management settings', 'إعدادات إدارة ملفات المستخدمين', 'settings')

ON CONFLICT (translation_key) DO UPDATE SET
  text_en = EXCLUDED.text_en,
  text_ar = EXCLUDED.text_ar,
  category = EXCLUDED.category;