-- Final comprehensive seed data with correct table structures

-- Create comprehensive innovators with correct column names
INSERT INTO innovators (id, user_id, innovation_background, areas_of_interest, experience_level, total_ideas_submitted, total_ideas_approved, innovation_score) VALUES 
(gen_random_uuid(), '8066cfaf-4a91-4985-922b-74f6a286c441', 'مدير تقني في شركة تقنية كبرى مع خبرة 8 سنوات في تطوير الحلول الذكية والتحول الرقمي', ARRAY['الذكاء الاصطناعي', 'إنترنت الأشياء', 'البلوك تشين', 'التحول الرقمي'], 'senior', 12, 9, 85.5),
(gen_random_uuid(), 'fa80bed2-ed61-4c27-8941-f713cf050944', 'مديرة مشاريع في القطاع الحكومي مع خبرة 10 سنوات في إدارة المشاريع الاستراتيجية وتطوير العمليات', ARRAY['إدارة المشاريع', 'تحسين العمليات', 'إدارة التغيير', 'التخطيط الاستراتيجي'], 'senior', 8, 6, 78.0);

-- Create realistic ideas with different statuses using correct priority level values
INSERT INTO ideas (id, title_ar, description_ar, solution_approach, implementation_plan, expected_impact, status, priority_level, innovator_id, challenge_id, focus_question_id, created_at) VALUES 
(gen_random_uuid(), 'تطبيق ذكي للخدمات الحكومية بالذكاء الاصطناعي', 'تطوير تطبيق محمول يستخدم الذكاء الاصطناعي لفهم استفسارات المواطنين وتوجيههم للخدمة المناسبة تلقائياً مع دعم معالجة اللغة الطبيعية باللغة العربية', 'استخدام نماذج الذكاء الاصطناعي المدربة على البيانات الحكومية مع واجهة محادثة ذكية', 'المرحلة الأولى: تطوير النموذج الأساسي، المرحلة الثانية: التكامل مع الأنظمة، المرحلة الثالثة: الإطلاق التجريبي', 'تحسين تجربة المواطن بنسبة 40% وتقليل وقت الحصول على الخدمات بنسبة 60%', 'under_review', 'عالي', (SELECT id FROM innovators WHERE user_id = '8066cfaf-4a91-4985-922b-74f6a286c441'), (SELECT id FROM challenges WHERE title_ar = 'منصة الخدمات الحكومية الموحدة' LIMIT 1), (SELECT id FROM focus_questions LIMIT 1), '2024-03-15'),

(gen_random_uuid(), 'نظام التشخيص بالصور الطبية المدعوم بالذكاء الاصطناعي', 'تطوير نظام متقدم لتحليل الصور الطبية (أشعة سينية، رنين مغناطيسي، أشعة مقطعية) باستخدام خوارزميات التعلم العميق للكشف المبكر عن الأمراض', 'استخدام شبكات التعلم العميق CNN المدربة على مجموعات بيانات طبية كبيرة مع تقنيات Transfer Learning', 'بناء قاعدة بيانات طبية، تدريب النماذج، اختبار الدقة، التكامل مع الأنظمة الطبية الحالية', 'تحسين دقة التشخيص بنسبة 25% وتقليل وقت التشخيص بنسبة 50%', 'approved', 'عالي', (SELECT id FROM innovators WHERE user_id = 'fa80bed2-ed61-4c27-8941-f713cf050944'), (SELECT id FROM challenges WHERE title_ar = 'نظام الذكاء الاصطناعي للتشخيص الطبي' LIMIT 1), (SELECT id FROM focus_questions LIMIT 1 OFFSET 1), '2024-03-10'),

(gen_random_uuid(), 'منصة التعلم التفاعلي بالواقع المعزز', 'تطوير منصة تعليمية تستخدم تقنيات الواقع المعزز لإنشاء تجارب تعليمية تفاعلية ثلاثية الأبعاد', 'دمج تقنيات AR مع المناهج التعليمية التقليدية لإنشاء بيئة تعلم متطورة', 'تصميم النماذج ثلاثية الأبعاد، تطوير التطبيق، اختبار المستخدمين، التطبيق التجريبي', 'زيادة التفاعل الطلابي بنسبة 60% وتحسين الفهم بنسبة 35%', 'draft', 'متوسط', (SELECT id FROM innovators WHERE user_id = '8066cfaf-4a91-4985-922b-74f6a286c441'), (SELECT id FROM challenges WHERE title_ar = 'منصة التعليم التفاعلي بالواقع الافتراضي' LIMIT 1), (SELECT id FROM focus_questions LIMIT 1 OFFSET 2), '2024-03-20');

-- Create idea evaluations with realistic assessments
INSERT INTO idea_evaluations (id, idea_id, evaluator_id, technical_feasibility, financial_viability, market_potential, strategic_alignment, innovation_level, implementation_complexity, strengths, weaknesses, recommendations, next_steps, evaluator_type) VALUES 
(gen_random_uuid(), (SELECT id FROM ideas WHERE title_ar = 'تطبيق ذكي للخدمات الحكومية بالذكاء الاصطناعي'), '8066cfaf-4a91-4985-922b-74f6a286c441', 8, 7, 9, 9, 8, 6, 'فكرة مبتكرة ومناسبة للسياق المحلي، إمكانية تطبيق عالية، تلبي احتياجات حقيقية للمواطنين', 'تحتاج لموارد تقنية كبيرة، التكامل مع الأنظمة الحالية قد يكون معقداً، تتطلب تدريب مكثف للفرق', 'البدء بنموذج أولي محدود ثم التوسع تدريجياً، التركيز على أهم الخدمات أولاً', 'إعداد دراسة جدوى تفصيلية وتحديد المتطلبات التقنية والميزانية المطلوبة', 'technical_expert'),

(gen_random_uuid(), (SELECT id FROM ideas WHERE title_ar = 'نظام التشخيص بالصور الطبية المدعوم بالذكاء الاصطناعي'), 'fa80bed2-ed61-4c27-8941-f713cf050944', 9, 8, 8, 10, 9, 8, 'تأثير كبير على جودة الرعاية الصحية، تقنية متقدمة ومطلوبة بشدة، ستوفر كثيراً من الوقت والجهد', 'تتطلب بيانات طبية كبيرة ومعتمدة، حاجة لموافقات تنظيمية صارمة، تكلفة عالية للتطوير', 'التعاون مع المستشفيات الكبرى والجامعات الطبية، الحصول على الشهادات اللازمة', 'الحصول على الموافقات اللازمة وبناء شراكات استراتيجية مع القطاع الصحي', 'domain_expert');

-- Create events with comprehensive data
INSERT INTO events (id, title_ar, description_ar, event_date, start_time, end_time, format, location, virtual_link, event_type, max_participants, status, budget, event_manager_id, campaign_id, challenge_id, sector_id) VALUES 
(gen_random_uuid(), 'منتدى الابتكار الرقمي الأول', 'منتدى متخصص يجمع الخبراء والمبتكرين لمناقشة أحدث الاتجاهات في التحول الرقمي والذكاء الاصطناعي', '2024-05-15', '09:00', '17:00', 'hybrid', 'مركز الملك عبدالعزيز الثقافي، الظهران', 'https://meet.gov.sa/digital-forum-2024', 'forum', 300, 'scheduled', 500000, 'fa80bed2-ed61-4c27-8941-f713cf050944', (SELECT id FROM campaigns LIMIT 1), (SELECT id FROM challenges WHERE title_ar = 'منصة الخدمات الحكومية الموحدة' LIMIT 1), (SELECT id FROM sectors WHERE name = 'Smart Cities' LIMIT 1)),

(gen_random_uuid(), 'ورشة تطوير الحلول الصحية الذكية', 'ورشة عمل تفاعلية لتطوير نماذج أولية للحلول الصحية باستخدام الذكاء الاصطناعي مع خبراء من القطاع الطبي', '2024-07-20', '10:00', '16:00', 'in_person', 'مدينة الملك عبدالعزيز للعلوم والتقنية، الرياض', NULL, 'workshop', 50, 'scheduled', 150000, '8066cfaf-4a91-4985-922b-74f6a286c441', (SELECT id FROM campaigns LIMIT 1 OFFSET 1), (SELECT id FROM challenges WHERE title_ar = 'نظام الذكاء الاصطناعي للتشخيص الطبي' LIMIT 1), (SELECT id FROM sectors WHERE name = 'Healthcare Innovation' LIMIT 1));